// @generated by protoc-gen-es v2.15.0
// @generated from file salesorder/v1/devices.proto (package salesorder.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_salesorder_v1_common } from "./common_pb";

/**
 * Describes the file salesorder/v1/devices.proto.
 */
export const file_salesorder_v1_devices = /*@__PURE__*/
  fileDesc("ChtzYWxlc29yZGVyL3YxL2RldmljZXMucHJvdG8SDXNhbGVzb3JkZXIudjEiUQoVUmVnaXN0ZXJEZXZpY2VSZXF1ZXN0EhAKCHBsYXRmb3JtGAEgASgJEhEKCWZjbV90b2tlbhgCIAEoCRITCgtkZXZpY2VfbmFtZRgDIAEoCSIrChZSZWdpc3RlckRldmljZVJlc3BvbnNlEhEKCWRldmljZV9pZBgBIAEoCSIsChdVbnJlZ2lzdGVyRGV2aWNlUmVxdWVzdBIRCglmY21fdG9rZW4YASABKAkiGgoYVW5yZWdpc3RlckRldmljZVJlc3BvbnNlMtMBCg1EZXZpY2VTZXJ2aWNlEl0KDlJlZ2lzdGVyRGV2aWNlEiQuc2FsZXNvcmRlci52MS5SZWdpc3RlckRldmljZVJlcXVlc3QaJS5zYWxlc29yZGVyLnYxLlJlZ2lzdGVyRGV2aWNlUmVzcG9uc2USYwoQVW5yZWdpc3RlckRldmljZRImLnNhbGVzb3JkZXIudjEuVW5yZWdpc3RlckRldmljZVJlcXVlc3QaJy5zYWxlc29yZGVyLnYxLlVucmVnaXN0ZXJEZXZpY2VSZXNwb25zZUJZWldnaXRodWIuY29tL3NhbGVzb3JkZXIvc2FsZXMtb3JkZXItMS4wL2JhY2tlbmQvaW50ZXJuYWwvcHJvdG8vc2FsZXNvcmRlci92MTtzYWxlc29yZGVydjFiBnByb3RvMw", [file_salesorder_v1_common]);

/**
 * Describes the message salesorder.v1.RegisterDeviceRequest.
 * Use `create(RegisterDeviceRequestSchema)` to create a new message.
 */
export const RegisterDeviceRequestSchema = /*@__PURE__*/
  messageDesc(file_salesorder_v1_devices, 0);

/**
 * Describes the message salesorder.v1.RegisterDeviceResponse.
 * Use `create(RegisterDeviceResponseSchema)` to create a new message.
 */
export const RegisterDeviceResponseSchema = /*@__PURE__*/
  messageDesc(file_salesorder_v1_devices, 1);

/**
 * Describes the message salesorder.v1.UnregisterDeviceRequest.
 * Use `create(UnregisterDeviceRequestSchema)` to create a new message.
 */
export const UnregisterDeviceRequestSchema = /*@__PURE__*/
  messageDesc(file_salesorder_v1_devices, 2);

/**
 * Describes the message salesorder.v1.UnregisterDeviceResponse.
 * Use `create(UnregisterDeviceResponseSchema)` to create a new message.
 */
export const UnregisterDeviceResponseSchema = /*@__PURE__*/
  messageDesc(file_salesorder_v1_devices, 3);

/**
 * DeviceService:裝置 FCM token 註冊/註銷(07 計畫 Task 4.3.4)。
 *
 * @generated from service salesorder.v1.DeviceService
 */
export const DeviceService = /*@__PURE__*/
  serviceDesc(file_salesorder_v1_devices, 0);

