// @generated by protoc-gen-es v2.15.0
// @generated from file salesorder/v1/salesorder.proto (package salesorder.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salesorder/v1/salesorder.proto.
 */
export declare const file_salesorder_v1_salesorder: GenFile;

/**
 * SalesOrder:訂單主檔。
 *
 * @generated from message salesorder.v1.SalesOrder
 */
export declare type SalesOrder = Message<"salesorder.v1.SalesOrder"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string company_id = 2;
   */
  companyId: string;

  /**
   * 可空
   *
   * @generated from field: string department_id = 3;
   */
  departmentId: string;

  /**
   * 系統取號,建立後不可改
   *
   * @generated from field: string order_no = 4;
   */
  orderNo: string;

  /**
   * @generated from field: string customer_id = 5;
   */
  customerId: string;

  /**
   * 訂單來源碼(metadicts order_source,如 W/A),建立後不可改
   *
   * @generated from field: string source = 6;
   */
  source: string;

  /**
   * pending/processing/completed/cancelled/voided
   *
   * @generated from field: string status = 7;
   */
  status: string;

  /**
   * 可空(RFC3339 date)
   *
   * @generated from field: string expected_delivery_date = 8;
   */
  expectedDeliveryDate: string;

  /**
   * 可空
   *
   * @generated from field: string sales_rep_id = 9;
   */
  salesRepId: string;

  /**
   * 可空
   *
   * @generated from field: string note = 10;
   */
  note: string;

  /**
   * 可空(RFC3339,派車域寫入)
   *
   * @generated from field: string dispatched_at = 11;
   */
  dispatchedAt: string;

  /**
   * 可空
   *
   * @generated from field: string dispatched_by = 12;
   */
  dispatchedBy: string;

  /**
   * 可空(取消派車保留看板位置)
   *
   * @generated from field: string route_id = 13;
   */
  routeId: string;

  /**
   * 看板順序(0 = 未排)
   *
   * @generated from field: int32 delivery_sequence = 14;
   */
  deliverySequence: number;

  /**
   * 樂觀鎖
   *
   * @generated from field: int32 version = 15;
   */
  version: number;

  /**
   * RFC3339
   *
   * @generated from field: string created_at = 16;
   */
  createdAt: string;

  /**
   * RFC3339
   *
   * @generated from field: string updated_at = 17;
   */
  updatedAt: string;

  /**
   * RFC3339(可空;include_deleted 時回傳)
   *
   * @generated from field: string deleted_at = 18;
   */
  deletedAt: string;
};

/**
 * Describes the message salesorder.v1.SalesOrder.
 * Use `create(SalesOrderSchema)` to create a new message.
 */
export declare const SalesOrderSchema: GenMessage<SalesOrder>;

/**
 * SalesOrderItem:訂單明細(不含金額)。
 *
 * @generated from message salesorder.v1.SalesOrderItem
 */
export declare type SalesOrderItem = Message<"salesorder.v1.SalesOrderItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 可空(手打品名無關聯)
   *
   * @generated from field: string product_id = 2;
   */
  productId: string;

  /**
   * 名稱快照
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * 十進位文字
   *
   * @generated from field: string qty = 4;
   */
  qty: string;

  /**
   * 選用單位
   *
   * @generated from field: string unit = 5;
   */
  unit: string;

  /**
   * 十進位文字,換算基本單位後數量
   *
   * @generated from field: string base_qty = 6;
   */
  baseQty: string;

  /**
   * 可空
   *
   * @generated from field: string processing_spec_id = 7;
   */
  processingSpecId: string;

  /**
   * 可空
   *
   * @generated from field: string special_cut_note = 8;
   */
  specialCutNote: string;

  /**
   * 可空
   *
   * @generated from field: string warehouse_id = 9;
   */
  warehouseId: string;

  /**
   * @generated from field: int32 sort_order = 10;
   */
  sortOrder: number;
};

/**
 * Describes the message salesorder.v1.SalesOrderItem.
 * Use `create(SalesOrderItemSchema)` to create a new message.
 */
export declare const SalesOrderItemSchema: GenMessage<SalesOrderItem>;

/**
 * SalesOrderEvent:訂單異動事件(僅追加)。
 *
 * @generated from message salesorder.v1.SalesOrderEvent
 */
export declare type SalesOrderEvent = Message<"salesorder.v1.SalesOrderEvent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * create/edit/dispatch/dispatch_cancel/cancel/complete/void
   *
   * @generated from field: string event_type = 2;
   */
  eventType: string;

  /**
   * @generated from field: string actor_id = 3;
   */
  actorId: string;

  /**
   * 可空(dispatch_cancel/void 必填語意)
   *
   * @generated from field: string reason = 4;
   */
  reason: string;

  /**
   * JSON(可空,異動摘要)
   *
   * @generated from field: string payload = 5;
   */
  payload: string;

  /**
   * RFC3339
   *
   * @generated from field: string created_at = 6;
   */
  createdAt: string;
};

/**
 * Describes the message salesorder.v1.SalesOrderEvent.
 * Use `create(SalesOrderEventSchema)` to create a new message.
 */
export declare const SalesOrderEventSchema: GenMessage<SalesOrderEvent>;

/**
 * @generated from message salesorder.v1.ListOrdersRequest
 */
export declare type ListOrdersRequest = Message<"salesorder.v1.ListOrdersRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * 可空
   *
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * 可空
   *
   * @generated from field: string customer_id = 4;
   */
  customerId: string;

  /**
   * 可空
   *
   * @generated from field: string source = 5;
   */
  source: string;

  /**
   * 模糊比對 order_no/note
   *
   * @generated from field: string keyword = 6;
   */
  keyword: string;

  /**
   * @generated from field: bool include_deleted = 7;
   */
  includeDeleted: boolean;
};

/**
 * Describes the message salesorder.v1.ListOrdersRequest.
 * Use `create(ListOrdersRequestSchema)` to create a new message.
 */
export declare const ListOrdersRequestSchema: GenMessage<ListOrdersRequest>;

/**
 * @generated from message salesorder.v1.ListOrdersResponse
 */
export declare type ListOrdersResponse = Message<"salesorder.v1.ListOrdersResponse"> & {
  /**
   * @generated from field: repeated salesorder.v1.SalesOrder orders = 1;
   */
  orders: SalesOrder[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message salesorder.v1.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export declare const ListOrdersResponseSchema: GenMessage<ListOrdersResponse>;

/**
 * @generated from message salesorder.v1.GetOrderRequest
 */
export declare type GetOrderRequest = Message<"salesorder.v1.GetOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message salesorder.v1.GetOrderRequest.
 * Use `create(GetOrderRequestSchema)` to create a new message.
 */
export declare const GetOrderRequestSchema: GenMessage<GetOrderRequest>;

/**
 * @generated from message salesorder.v1.GetOrderResponse
 */
export declare type GetOrderResponse = Message<"salesorder.v1.GetOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;

  /**
   * @generated from field: repeated salesorder.v1.SalesOrderItem items = 2;
   */
  items: SalesOrderItem[];
};

/**
 * Describes the message salesorder.v1.GetOrderResponse.
 * Use `create(GetOrderResponseSchema)` to create a new message.
 */
export declare const GetOrderResponseSchema: GenMessage<GetOrderResponse>;

/**
 * @generated from message salesorder.v1.OrderItemInput
 */
export declare type OrderItemInput = Message<"salesorder.v1.OrderItemInput"> & {
  /**
   * 可空(手打品名)
   *
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * 可空(手打品名,業務限定)
   *
   * @generated from field: string manual_name = 2;
   */
  manualName: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: string qty = 4;
   */
  qty: string;

  /**
   * @generated from field: string unit = 5;
   */
  unit: string;

  /**
   * 可空
   *
   * @generated from field: string processing_spec_id = 6;
   */
  processingSpecId: string;

  /**
   * 可空
   *
   * @generated from field: string special_cut_note = 7;
   */
  specialCutNote: string;

  /**
   * 可空
   *
   * @generated from field: string warehouse_id = 8;
   */
  warehouseId: string;

  /**
   * true 即同交易 upsert 客戶別名(4.2.2;需 product_id)
   *
   * @generated from field: bool save_alias = 9;
   */
  saveAlias: boolean;
};

/**
 * Describes the message salesorder.v1.OrderItemInput.
 * Use `create(OrderItemInputSchema)` to create a new message.
 */
export declare const OrderItemInputSchema: GenMessage<OrderItemInput>;

/**
 * @generated from message salesorder.v1.CreateOrderRequest
 */
export declare type CreateOrderRequest = Message<"salesorder.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * 可空(RFC3339 date)
   *
   * @generated from field: string expected_delivery_date = 3;
   */
  expectedDeliveryDate: string;

  /**
   * 可空
   *
   * @generated from field: string note = 4;
   */
  note: string;

  /**
   * 可空
   *
   * @generated from field: string sales_rep_id = 5;
   */
  salesRepId: string;

  /**
   * @generated from field: repeated salesorder.v1.OrderItemInput items = 6;
   */
  items: OrderItemInput[];
};

/**
 * Describes the message salesorder.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export declare const CreateOrderRequestSchema: GenMessage<CreateOrderRequest>;

/**
 * @generated from message salesorder.v1.CreateOrderResponse
 */
export declare type CreateOrderResponse = Message<"salesorder.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;
};

/**
 * Describes the message salesorder.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export declare const CreateOrderResponseSchema: GenMessage<CreateOrderResponse>;

/**
 * @generated from message salesorder.v1.UpdateOrderRequest
 */
export declare type UpdateOrderRequest = Message<"salesorder.v1.UpdateOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int32 version = 2;
   */
  version: number;

  /**
   * 可空(帶即改,不帶不動)
   *
   * @generated from field: string expected_delivery_date = 3;
   */
  expectedDeliveryDate: string;

  /**
   * 可空(帶即改,不帶不動)
   *
   * @generated from field: string note = 4;
   */
  note: string;

  /**
   * 空即不動明細,非空即整單替換
   *
   * @generated from field: repeated salesorder.v1.OrderItemInput items = 5;
   */
  items: OrderItemInput[];
};

/**
 * Describes the message salesorder.v1.UpdateOrderRequest.
 * Use `create(UpdateOrderRequestSchema)` to create a new message.
 */
export declare const UpdateOrderRequestSchema: GenMessage<UpdateOrderRequest>;

/**
 * @generated from message salesorder.v1.UpdateOrderResponse
 */
export declare type UpdateOrderResponse = Message<"salesorder.v1.UpdateOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;
};

/**
 * Describes the message salesorder.v1.UpdateOrderResponse.
 * Use `create(UpdateOrderResponseSchema)` to create a new message.
 */
export declare const UpdateOrderResponseSchema: GenMessage<UpdateOrderResponse>;

/**
 * @generated from message salesorder.v1.CancelOrderRequest
 */
export declare type CancelOrderRequest = Message<"salesorder.v1.CancelOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message salesorder.v1.CancelOrderRequest.
 * Use `create(CancelOrderRequestSchema)` to create a new message.
 */
export declare const CancelOrderRequestSchema: GenMessage<CancelOrderRequest>;

/**
 * @generated from message salesorder.v1.CancelOrderResponse
 */
export declare type CancelOrderResponse = Message<"salesorder.v1.CancelOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;
};

/**
 * Describes the message salesorder.v1.CancelOrderResponse.
 * Use `create(CancelOrderResponseSchema)` to create a new message.
 */
export declare const CancelOrderResponseSchema: GenMessage<CancelOrderResponse>;

/**
 * @generated from message salesorder.v1.CompleteOrderRequest
 */
export declare type CompleteOrderRequest = Message<"salesorder.v1.CompleteOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message salesorder.v1.CompleteOrderRequest.
 * Use `create(CompleteOrderRequestSchema)` to create a new message.
 */
export declare const CompleteOrderRequestSchema: GenMessage<CompleteOrderRequest>;

/**
 * @generated from message salesorder.v1.CompleteOrderResponse
 */
export declare type CompleteOrderResponse = Message<"salesorder.v1.CompleteOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;
};

/**
 * Describes the message salesorder.v1.CompleteOrderResponse.
 * Use `create(CompleteOrderResponseSchema)` to create a new message.
 */
export declare const CompleteOrderResponseSchema: GenMessage<CompleteOrderResponse>;

/**
 * @generated from message salesorder.v1.VoidOrderRequest
 */
export declare type VoidOrderRequest = Message<"salesorder.v1.VoidOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message salesorder.v1.VoidOrderRequest.
 * Use `create(VoidOrderRequestSchema)` to create a new message.
 */
export declare const VoidOrderRequestSchema: GenMessage<VoidOrderRequest>;

/**
 * @generated from message salesorder.v1.VoidOrderResponse
 */
export declare type VoidOrderResponse = Message<"salesorder.v1.VoidOrderResponse"> & {
  /**
   * @generated from field: salesorder.v1.SalesOrder order = 1;
   */
  order?: SalesOrder | undefined;
};

/**
 * Describes the message salesorder.v1.VoidOrderResponse.
 * Use `create(VoidOrderResponseSchema)` to create a new message.
 */
export declare const VoidOrderResponseSchema: GenMessage<VoidOrderResponse>;

/**
 * @generated from message salesorder.v1.DeleteOrderRequest
 */
export declare type DeleteOrderRequest = Message<"salesorder.v1.DeleteOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message salesorder.v1.DeleteOrderRequest.
 * Use `create(DeleteOrderRequestSchema)` to create a new message.
 */
export declare const DeleteOrderRequestSchema: GenMessage<DeleteOrderRequest>;

/**
 * @generated from message salesorder.v1.DeleteOrderResponse
 */
export declare type DeleteOrderResponse = Message<"salesorder.v1.DeleteOrderResponse"> & {
};

/**
 * Describes the message salesorder.v1.DeleteOrderResponse.
 * Use `create(DeleteOrderResponseSchema)` to create a new message.
 */
export declare const DeleteOrderResponseSchema: GenMessage<DeleteOrderResponse>;

/**
 * @generated from message salesorder.v1.ListOrderEventsRequest
 */
export declare type ListOrderEventsRequest = Message<"salesorder.v1.ListOrderEventsRequest"> & {
  /**
   * @generated from field: string sales_order_id = 1;
   */
  salesOrderId: string;

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;
};

/**
 * Describes the message salesorder.v1.ListOrderEventsRequest.
 * Use `create(ListOrderEventsRequestSchema)` to create a new message.
 */
export declare const ListOrderEventsRequestSchema: GenMessage<ListOrderEventsRequest>;

/**
 * @generated from message salesorder.v1.ListOrderEventsResponse
 */
export declare type ListOrderEventsResponse = Message<"salesorder.v1.ListOrderEventsResponse"> & {
  /**
   * @generated from field: repeated salesorder.v1.SalesOrderEvent events = 1;
   */
  events: SalesOrderEvent[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message salesorder.v1.ListOrderEventsResponse.
 * Use `create(ListOrderEventsResponseSchema)` to create a new message.
 */
export declare const ListOrderEventsResponseSchema: GenMessage<ListOrderEventsResponse>;

/**
 * SalesOrderService:銷售訂單管理。
 *
 * @generated from service salesorder.v1.SalesOrderService
 */
export declare const SalesOrderService: GenService<{
  /**
   * ListOrders:分頁查詢(預設排除軟刪除;status/customer_id/source/keyword 篩選)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.ListOrders
   */
  listOrders: {
    methodKind: "unary";
    input: typeof ListOrdersRequestSchema;
    output: typeof ListOrdersResponseSchema;
  },
  /**
   * GetOrder:以 id 取單筆(含明細)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.GetOrder
   */
  getOrder: {
    methodKind: "unary";
    input: typeof GetOrderRequestSchema;
    output: typeof GetOrderResponseSchema;
  },
  /**
   * CreateOrder:建立訂單(最小可用:客戶+來源+明細;取號+建單同交易)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
  /**
   * UpdateOrder:僅 pending 可編輯(攜帶 version 樂觀鎖)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.UpdateOrder
   */
  updateOrder: {
    methodKind: "unary";
    input: typeof UpdateOrderRequestSchema;
    output: typeof UpdateOrderResponseSchema;
  },
  /**
   * CancelOrder:僅 pending 可取消。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.CancelOrder
   */
  cancelOrder: {
    methodKind: "unary";
    input: typeof CancelOrderRequestSchema;
    output: typeof CancelOrderResponseSchema;
  },
  /**
   * CompleteOrder:僅 processing 可完成。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.CompleteOrder
   */
  completeOrder: {
    methodKind: "unary";
    input: typeof CompleteOrderRequestSchema;
    output: typeof CompleteOrderResponseSchema;
  },
  /**
   * VoidOrder:僅 completed 可作廢(dept_admin 以上 + 原因)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.VoidOrder
   */
  voidOrder: {
    methodKind: "unary";
    input: typeof VoidOrderRequestSchema;
    output: typeof VoidOrderResponseSchema;
  },
  /**
   * DeleteOrder:軟刪除(僅 pending/cancelled)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.DeleteOrder
   */
  deleteOrder: {
    methodKind: "unary";
    input: typeof DeleteOrderRequestSchema;
    output: typeof DeleteOrderResponseSchema;
  },
  /**
   * ListOrderEvents:異動軌跡查詢(升序)。
   *
   * @generated from rpc salesorder.v1.SalesOrderService.ListOrderEvents
   */
  listOrderEvents: {
    methodKind: "unary";
    input: typeof ListOrderEventsRequestSchema;
    output: typeof ListOrderEventsResponseSchema;
  },
}>;

