// Code generated by ent, DO NOT EDIT.

package logisticsdelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCompanyID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDepartmentID, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldRouteID, v))
}

// DriverID applies equality check predicate on the "driver_id" field. It's identical to DriverIDEQ.
func DriverID(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDriverID, v))
}

// VehicleID applies equality check predicate on the "vehicle_id" field. It's identical to VehicleIDEQ.
func VehicleID(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldVehicleID, v))
}

// AssignedBy applies equality check predicate on the "assigned_by" field. It's identical to AssignedByEQ.
func AssignedBy(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldAssignedBy, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldStatus, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldVersion, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCompletedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldCompanyID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldDepartmentID))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldRouteID, vs...))
}

// RouteIDGT applies the GT predicate on the "route_id" field.
func RouteIDGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldRouteID, v))
}

// RouteIDGTE applies the GTE predicate on the "route_id" field.
func RouteIDGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldRouteID, v))
}

// RouteIDLT applies the LT predicate on the "route_id" field.
func RouteIDLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldRouteID, v))
}

// RouteIDLTE applies the LTE predicate on the "route_id" field.
func RouteIDLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldRouteID, v))
}

// DriverIDEQ applies the EQ predicate on the "driver_id" field.
func DriverIDEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDriverID, v))
}

// DriverIDNEQ applies the NEQ predicate on the "driver_id" field.
func DriverIDNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldDriverID, v))
}

// DriverIDIn applies the In predicate on the "driver_id" field.
func DriverIDIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldDriverID, vs...))
}

// DriverIDNotIn applies the NotIn predicate on the "driver_id" field.
func DriverIDNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldDriverID, vs...))
}

// DriverIDGT applies the GT predicate on the "driver_id" field.
func DriverIDGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldDriverID, v))
}

// DriverIDGTE applies the GTE predicate on the "driver_id" field.
func DriverIDGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldDriverID, v))
}

// DriverIDLT applies the LT predicate on the "driver_id" field.
func DriverIDLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldDriverID, v))
}

// DriverIDLTE applies the LTE predicate on the "driver_id" field.
func DriverIDLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldDriverID, v))
}

// DriverIDIsNil applies the IsNil predicate on the "driver_id" field.
func DriverIDIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldDriverID))
}

// DriverIDNotNil applies the NotNil predicate on the "driver_id" field.
func DriverIDNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldDriverID))
}

// VehicleIDEQ applies the EQ predicate on the "vehicle_id" field.
func VehicleIDEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldVehicleID, v))
}

// VehicleIDNEQ applies the NEQ predicate on the "vehicle_id" field.
func VehicleIDNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldVehicleID, v))
}

// VehicleIDIn applies the In predicate on the "vehicle_id" field.
func VehicleIDIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldVehicleID, vs...))
}

// VehicleIDNotIn applies the NotIn predicate on the "vehicle_id" field.
func VehicleIDNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldVehicleID, vs...))
}

// VehicleIDGT applies the GT predicate on the "vehicle_id" field.
func VehicleIDGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldVehicleID, v))
}

// VehicleIDGTE applies the GTE predicate on the "vehicle_id" field.
func VehicleIDGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldVehicleID, v))
}

// VehicleIDLT applies the LT predicate on the "vehicle_id" field.
func VehicleIDLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldVehicleID, v))
}

// VehicleIDLTE applies the LTE predicate on the "vehicle_id" field.
func VehicleIDLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldVehicleID, v))
}

// VehicleIDIsNil applies the IsNil predicate on the "vehicle_id" field.
func VehicleIDIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldVehicleID))
}

// VehicleIDNotNil applies the NotNil predicate on the "vehicle_id" field.
func VehicleIDNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldVehicleID))
}

// AssignedByEQ applies the EQ predicate on the "assigned_by" field.
func AssignedByEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedByNEQ applies the NEQ predicate on the "assigned_by" field.
func AssignedByNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldAssignedBy, v))
}

// AssignedByIn applies the In predicate on the "assigned_by" field.
func AssignedByIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldAssignedBy, vs...))
}

// AssignedByNotIn applies the NotIn predicate on the "assigned_by" field.
func AssignedByNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldAssignedBy, vs...))
}

// AssignedByGT applies the GT predicate on the "assigned_by" field.
func AssignedByGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldAssignedBy, v))
}

// AssignedByGTE applies the GTE predicate on the "assigned_by" field.
func AssignedByGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldAssignedBy, v))
}

// AssignedByLT applies the LT predicate on the "assigned_by" field.
func AssignedByLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldAssignedBy, v))
}

// AssignedByLTE applies the LTE predicate on the "assigned_by" field.
func AssignedByLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldAssignedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldVersion, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldCompletedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LogisticsDelivery) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LogisticsDelivery) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LogisticsDelivery) predicate.LogisticsDelivery {
	return predicate.LogisticsDelivery(sql.NotPredicates(p))
}
