// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// EmployeeNo applies equality check predicate on the "employee_no" field. It's identical to EmployeeNoEQ.
func EmployeeNo(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmployeeNo, v))
}

// IsCustomer applies equality check predicate on the "is_customer" field. It's identical to IsCustomerEQ.
func IsCustomer(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsCustomer, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCustomerID, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsPrimary, v))
}

// SystemGenerated applies equality check predicate on the "system_generated" field. It's identical to SystemGeneratedEQ.
func SystemGenerated(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSystemGenerated, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccountName, v))
}

// TokenVersion applies equality check predicate on the "token_version" field. It's identical to TokenVersionEQ.
func TokenVersion(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTokenVersion, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// MustChangePassword applies equality check predicate on the "must_change_password" field. It's identical to MustChangePasswordEQ.
func MustChangePassword(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMustChangePassword, v))
}

// TempPasswordExpiresAt applies equality check predicate on the "temp_password_expires_at" field. It's identical to TempPasswordExpiresAtEQ.
func TempPasswordExpiresAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTempPasswordExpiresAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldStatus, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRole, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPhone, v))
}

// EmployeeNoEQ applies the EQ predicate on the "employee_no" field.
func EmployeeNoEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmployeeNo, v))
}

// EmployeeNoNEQ applies the NEQ predicate on the "employee_no" field.
func EmployeeNoNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmployeeNo, v))
}

// EmployeeNoIn applies the In predicate on the "employee_no" field.
func EmployeeNoIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmployeeNo, vs...))
}

// EmployeeNoNotIn applies the NotIn predicate on the "employee_no" field.
func EmployeeNoNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmployeeNo, vs...))
}

// EmployeeNoGT applies the GT predicate on the "employee_no" field.
func EmployeeNoGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmployeeNo, v))
}

// EmployeeNoGTE applies the GTE predicate on the "employee_no" field.
func EmployeeNoGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmployeeNo, v))
}

// EmployeeNoLT applies the LT predicate on the "employee_no" field.
func EmployeeNoLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmployeeNo, v))
}

// EmployeeNoLTE applies the LTE predicate on the "employee_no" field.
func EmployeeNoLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmployeeNo, v))
}

// EmployeeNoContains applies the Contains predicate on the "employee_no" field.
func EmployeeNoContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmployeeNo, v))
}

// EmployeeNoHasPrefix applies the HasPrefix predicate on the "employee_no" field.
func EmployeeNoHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmployeeNo, v))
}

// EmployeeNoHasSuffix applies the HasSuffix predicate on the "employee_no" field.
func EmployeeNoHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmployeeNo, v))
}

// EmployeeNoIsNil applies the IsNil predicate on the "employee_no" field.
func EmployeeNoIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmployeeNo))
}

// EmployeeNoNotNil applies the NotNil predicate on the "employee_no" field.
func EmployeeNoNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmployeeNo))
}

// EmployeeNoEqualFold applies the EqualFold predicate on the "employee_no" field.
func EmployeeNoEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmployeeNo, v))
}

// EmployeeNoContainsFold applies the ContainsFold predicate on the "employee_no" field.
func EmployeeNoContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmployeeNo, v))
}

// IsCustomerEQ applies the EQ predicate on the "is_customer" field.
func IsCustomerEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsCustomer, v))
}

// IsCustomerNEQ applies the NEQ predicate on the "is_customer" field.
func IsCustomerNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsCustomer, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldCustomerID))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsPrimary, v))
}

// SystemGeneratedEQ applies the EQ predicate on the "system_generated" field.
func SystemGeneratedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSystemGenerated, v))
}

// SystemGeneratedNEQ applies the NEQ predicate on the "system_generated" field.
func SystemGeneratedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSystemGenerated, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameIsNil applies the IsNil predicate on the "account_name" field.
func AccountNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAccountName))
}

// AccountNameNotNil applies the NotNil predicate on the "account_name" field.
func AccountNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAccountName))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAccountName, v))
}

// TokenVersionEQ applies the EQ predicate on the "token_version" field.
func TokenVersionEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTokenVersion, v))
}

// TokenVersionNEQ applies the NEQ predicate on the "token_version" field.
func TokenVersionNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTokenVersion, v))
}

// TokenVersionIn applies the In predicate on the "token_version" field.
func TokenVersionIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldTokenVersion, vs...))
}

// TokenVersionNotIn applies the NotIn predicate on the "token_version" field.
func TokenVersionNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTokenVersion, vs...))
}

// TokenVersionGT applies the GT predicate on the "token_version" field.
func TokenVersionGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldTokenVersion, v))
}

// TokenVersionGTE applies the GTE predicate on the "token_version" field.
func TokenVersionGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTokenVersion, v))
}

// TokenVersionLT applies the LT predicate on the "token_version" field.
func TokenVersionLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldTokenVersion, v))
}

// TokenVersionLTE applies the LTE predicate on the "token_version" field.
func TokenVersionLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTokenVersion, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// MustChangePasswordEQ applies the EQ predicate on the "must_change_password" field.
func MustChangePasswordEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMustChangePassword, v))
}

// MustChangePasswordNEQ applies the NEQ predicate on the "must_change_password" field.
func MustChangePasswordNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMustChangePassword, v))
}

// TempPasswordExpiresAtEQ applies the EQ predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtNEQ applies the NEQ predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtIn applies the In predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldTempPasswordExpiresAt, vs...))
}

// TempPasswordExpiresAtNotIn applies the NotIn predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTempPasswordExpiresAt, vs...))
}

// TempPasswordExpiresAtGT applies the GT predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtGTE applies the GTE predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtLT applies the LT predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtLTE applies the LTE predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTempPasswordExpiresAt, v))
}

// TempPasswordExpiresAtIsNil applies the IsNil predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTempPasswordExpiresAt))
}

// TempPasswordExpiresAtNotNil applies the NotNil predicate on the "temp_password_expires_at" field.
func TempPasswordExpiresAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTempPasswordExpiresAt))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.Company) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCompanyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newDepartmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
