services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesorder
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8
    ports:
      - "6379:6379"

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3001:3000"

volumes:
  postgres_data:
