// Code generated by ent, DO NOT EDIT.

package productunit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldID, id))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldProductID, v))
}

// UnitCode applies equality check predicate on the "unit_code" field. It's identical to UnitCodeEQ.
func UnitCode(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldUnitCode, v))
}

// ConversionRate applies equality check predicate on the "conversion_rate" field. It's identical to ConversionRateEQ.
func ConversionRate(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldConversionRate, v))
}

// IsBase applies equality check predicate on the "is_base" field. It's identical to IsBaseEQ.
func IsBase(v bool) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldIsBase, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldSortOrder, v))
}

// SizeDesc applies equality check predicate on the "size_desc" field. It's identical to SizeDescEQ.
func SizeDesc(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldSizeDesc, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldProductID, v))
}

// UnitCodeEQ applies the EQ predicate on the "unit_code" field.
func UnitCodeEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldUnitCode, v))
}

// UnitCodeNEQ applies the NEQ predicate on the "unit_code" field.
func UnitCodeNEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldUnitCode, v))
}

// UnitCodeIn applies the In predicate on the "unit_code" field.
func UnitCodeIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldUnitCode, vs...))
}

// UnitCodeNotIn applies the NotIn predicate on the "unit_code" field.
func UnitCodeNotIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldUnitCode, vs...))
}

// UnitCodeGT applies the GT predicate on the "unit_code" field.
func UnitCodeGT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldUnitCode, v))
}

// UnitCodeGTE applies the GTE predicate on the "unit_code" field.
func UnitCodeGTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldUnitCode, v))
}

// UnitCodeLT applies the LT predicate on the "unit_code" field.
func UnitCodeLT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldUnitCode, v))
}

// UnitCodeLTE applies the LTE predicate on the "unit_code" field.
func UnitCodeLTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldUnitCode, v))
}

// UnitCodeContains applies the Contains predicate on the "unit_code" field.
func UnitCodeContains(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContains(FieldUnitCode, v))
}

// UnitCodeHasPrefix applies the HasPrefix predicate on the "unit_code" field.
func UnitCodeHasPrefix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasPrefix(FieldUnitCode, v))
}

// UnitCodeHasSuffix applies the HasSuffix predicate on the "unit_code" field.
func UnitCodeHasSuffix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasSuffix(FieldUnitCode, v))
}

// UnitCodeEqualFold applies the EqualFold predicate on the "unit_code" field.
func UnitCodeEqualFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEqualFold(FieldUnitCode, v))
}

// UnitCodeContainsFold applies the ContainsFold predicate on the "unit_code" field.
func UnitCodeContainsFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContainsFold(FieldUnitCode, v))
}

// ConversionRateEQ applies the EQ predicate on the "conversion_rate" field.
func ConversionRateEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldConversionRate, v))
}

// ConversionRateNEQ applies the NEQ predicate on the "conversion_rate" field.
func ConversionRateNEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldConversionRate, v))
}

// ConversionRateIn applies the In predicate on the "conversion_rate" field.
func ConversionRateIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldConversionRate, vs...))
}

// ConversionRateNotIn applies the NotIn predicate on the "conversion_rate" field.
func ConversionRateNotIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldConversionRate, vs...))
}

// ConversionRateGT applies the GT predicate on the "conversion_rate" field.
func ConversionRateGT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldConversionRate, v))
}

// ConversionRateGTE applies the GTE predicate on the "conversion_rate" field.
func ConversionRateGTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldConversionRate, v))
}

// ConversionRateLT applies the LT predicate on the "conversion_rate" field.
func ConversionRateLT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldConversionRate, v))
}

// ConversionRateLTE applies the LTE predicate on the "conversion_rate" field.
func ConversionRateLTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldConversionRate, v))
}

// ConversionRateContains applies the Contains predicate on the "conversion_rate" field.
func ConversionRateContains(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContains(FieldConversionRate, v))
}

// ConversionRateHasPrefix applies the HasPrefix predicate on the "conversion_rate" field.
func ConversionRateHasPrefix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasPrefix(FieldConversionRate, v))
}

// ConversionRateHasSuffix applies the HasSuffix predicate on the "conversion_rate" field.
func ConversionRateHasSuffix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasSuffix(FieldConversionRate, v))
}

// ConversionRateEqualFold applies the EqualFold predicate on the "conversion_rate" field.
func ConversionRateEqualFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEqualFold(FieldConversionRate, v))
}

// ConversionRateContainsFold applies the ContainsFold predicate on the "conversion_rate" field.
func ConversionRateContainsFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContainsFold(FieldConversionRate, v))
}

// IsBaseEQ applies the EQ predicate on the "is_base" field.
func IsBaseEQ(v bool) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldIsBase, v))
}

// IsBaseNEQ applies the NEQ predicate on the "is_base" field.
func IsBaseNEQ(v bool) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldIsBase, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldSortOrder, v))
}

// SizeDescEQ applies the EQ predicate on the "size_desc" field.
func SizeDescEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldSizeDesc, v))
}

// SizeDescNEQ applies the NEQ predicate on the "size_desc" field.
func SizeDescNEQ(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldSizeDesc, v))
}

// SizeDescIn applies the In predicate on the "size_desc" field.
func SizeDescIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldSizeDesc, vs...))
}

// SizeDescNotIn applies the NotIn predicate on the "size_desc" field.
func SizeDescNotIn(vs ...string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldSizeDesc, vs...))
}

// SizeDescGT applies the GT predicate on the "size_desc" field.
func SizeDescGT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldSizeDesc, v))
}

// SizeDescGTE applies the GTE predicate on the "size_desc" field.
func SizeDescGTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldSizeDesc, v))
}

// SizeDescLT applies the LT predicate on the "size_desc" field.
func SizeDescLT(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldSizeDesc, v))
}

// SizeDescLTE applies the LTE predicate on the "size_desc" field.
func SizeDescLTE(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldSizeDesc, v))
}

// SizeDescContains applies the Contains predicate on the "size_desc" field.
func SizeDescContains(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContains(FieldSizeDesc, v))
}

// SizeDescHasPrefix applies the HasPrefix predicate on the "size_desc" field.
func SizeDescHasPrefix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasPrefix(FieldSizeDesc, v))
}

// SizeDescHasSuffix applies the HasSuffix predicate on the "size_desc" field.
func SizeDescHasSuffix(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldHasSuffix(FieldSizeDesc, v))
}

// SizeDescIsNil applies the IsNil predicate on the "size_desc" field.
func SizeDescIsNil() predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIsNull(FieldSizeDesc))
}

// SizeDescNotNil applies the NotNil predicate on the "size_desc" field.
func SizeDescNotNil() predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotNull(FieldSizeDesc))
}

// SizeDescEqualFold applies the EqualFold predicate on the "size_desc" field.
func SizeDescEqualFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEqualFold(FieldSizeDesc, v))
}

// SizeDescContainsFold applies the ContainsFold predicate on the "size_desc" field.
func SizeDescContainsFold(v string) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldContainsFold(FieldSizeDesc, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductUnit {
	return predicate.ProductUnit(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductUnit) predicate.ProductUnit {
	return predicate.ProductUnit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductUnit) predicate.ProductUnit {
	return predicate.ProductUnit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductUnit) predicate.ProductUnit {
	return predicate.ProductUnit(sql.NotPredicates(p))
}
