// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/customer"
)

// Customer is the model entity for the Customer schema.
type Customer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CompanyID holds the value of the "company_id" field.
	CompanyID int `json:"company_id,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID *int `json:"department_id,omitempty"`
	// CustomerCode holds the value of the "customer_code" field.
	CustomerCode string `json:"customer_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID string `json:"tax_id,omitempty"`
	// PaymentMethodID holds the value of the "payment_method_id" field.
	PaymentMethodID *int `json:"payment_method_id,omitempty"`
	// SettlementMethodID holds the value of the "settlement_method_id" field.
	SettlementMethodID *int `json:"settlement_method_id,omitempty"`
	// CustomerTypeID holds the value of the "customer_type_id" field.
	CustomerTypeID *int `json:"customer_type_id,omitempty"`
	// InvoiceTypeID holds the value of the "invoice_type_id" field.
	InvoiceTypeID *int `json:"invoice_type_id,omitempty"`
	// DefaultSalesRepID holds the value of the "default_sales_rep_id" field.
	DefaultSalesRepID *int `json:"default_sales_rep_id,omitempty"`
	// PreferredDeliveryDays holds the value of the "preferred_delivery_days" field.
	PreferredDeliveryDays []bool `json:"preferred_delivery_days,omitempty"`
	// PromoTagIds holds the value of the "promo_tag_ids" field.
	PromoTagIds []int `json:"promo_tag_ids,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int `json:"updated_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Customer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customer.FieldPreferredDeliveryDays, customer.FieldPromoTagIds:
			values[i] = new([]byte)
		case customer.FieldID, customer.FieldCompanyID, customer.FieldDepartmentID, customer.FieldPaymentMethodID, customer.FieldSettlementMethodID, customer.FieldCustomerTypeID, customer.FieldInvoiceTypeID, customer.FieldDefaultSalesRepID, customer.FieldCreatedBy, customer.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case customer.FieldCustomerCode, customer.FieldName, customer.FieldTaxID:
			values[i] = new(sql.NullString)
		case customer.FieldCreatedAt, customer.FieldUpdatedAt, customer.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Customer fields.
func (_m *Customer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case customer.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				_m.CompanyID = int(value.Int64)
			}
		case customer.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = new(int)
				*_m.DepartmentID = int(value.Int64)
			}
		case customer.FieldCustomerCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_code", values[i])
			} else if value.Valid {
				_m.CustomerCode = value.String
			}
		case customer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case customer.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = value.String
			}
		case customer.FieldPaymentMethodID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method_id", values[i])
			} else if value.Valid {
				_m.PaymentMethodID = new(int)
				*_m.PaymentMethodID = int(value.Int64)
			}
		case customer.FieldSettlementMethodID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_method_id", values[i])
			} else if value.Valid {
				_m.SettlementMethodID = new(int)
				*_m.SettlementMethodID = int(value.Int64)
			}
		case customer.FieldCustomerTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field customer_type_id", values[i])
			} else if value.Valid {
				_m.CustomerTypeID = new(int)
				*_m.CustomerTypeID = int(value.Int64)
			}
		case customer.FieldInvoiceTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_type_id", values[i])
			} else if value.Valid {
				_m.InvoiceTypeID = new(int)
				*_m.InvoiceTypeID = int(value.Int64)
			}
		case customer.FieldDefaultSalesRepID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_sales_rep_id", values[i])
			} else if value.Valid {
				_m.DefaultSalesRepID = new(int)
				*_m.DefaultSalesRepID = int(value.Int64)
			}
		case customer.FieldPreferredDeliveryDays:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field preferred_delivery_days", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PreferredDeliveryDays); err != nil {
					return fmt.Errorf("unmarshal field preferred_delivery_days: %w", err)
				}
			}
		case customer.FieldPromoTagIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field promo_tag_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PromoTagIds); err != nil {
					return fmt.Errorf("unmarshal field promo_tag_ids: %w", err)
				}
			}
		case customer.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = int(value.Int64)
			}
		case customer.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = int(value.Int64)
			}
		case customer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case customer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case customer.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Customer.
// This includes values selected through modifiers, order, etc.
func (_m *Customer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Customer.
// Note that you need to call Customer.Unwrap() before calling this method if this Customer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Customer) Update() *CustomerUpdateOne {
	return NewCustomerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Customer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Customer) Unwrap() *Customer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Customer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Customer) String() string {
	var builder strings.Builder
	builder.WriteString("Customer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompanyID))
	builder.WriteString(", ")
	if v := _m.DepartmentID; v != nil {
		builder.WriteString("department_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("customer_code=")
	builder.WriteString(_m.CustomerCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("tax_id=")
	builder.WriteString(_m.TaxID)
	builder.WriteString(", ")
	if v := _m.PaymentMethodID; v != nil {
		builder.WriteString("payment_method_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SettlementMethodID; v != nil {
		builder.WriteString("settlement_method_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CustomerTypeID; v != nil {
		builder.WriteString("customer_type_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InvoiceTypeID; v != nil {
		builder.WriteString("invoice_type_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DefaultSalesRepID; v != nil {
		builder.WriteString("default_sales_rep_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("preferred_delivery_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreferredDeliveryDays))
	builder.WriteString(", ")
	builder.WriteString("promo_tag_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromoTagIds))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Customers is a parsable slice of Customer.
type Customers []*Customer
