// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/fleetdelivery"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// FleetDeliveryUpdate is the builder for updating FleetDelivery entities.
type FleetDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *FleetDeliveryMutation
}

// Where appends a list predicates to the FleetDeliveryUpdate builder.
func (_u *FleetDeliveryUpdate) Where(ps ...predicate.FleetDelivery) *FleetDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *FleetDeliveryUpdate) SetCompanyID(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableCompanyID(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *FleetDeliveryUpdate) AddCompanyID(v int) *FleetDeliveryUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *FleetDeliveryUpdate) SetDepartmentID(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableDepartmentID(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *FleetDeliveryUpdate) AddDepartmentID(v int) *FleetDeliveryUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *FleetDeliveryUpdate) ClearDepartmentID() *FleetDeliveryUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *FleetDeliveryUpdate) SetRouteID(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetRouteID()
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableRouteID(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// AddRouteID adds value to the "route_id" field.
func (_u *FleetDeliveryUpdate) AddRouteID(v int) *FleetDeliveryUpdate {
	_u.mutation.AddRouteID(v)
	return _u
}

// SetDriverID sets the "driver_id" field.
func (_u *FleetDeliveryUpdate) SetDriverID(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetDriverID()
	_u.mutation.SetDriverID(v)
	return _u
}

// SetNillableDriverID sets the "driver_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableDriverID(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetDriverID(*v)
	}
	return _u
}

// AddDriverID adds value to the "driver_id" field.
func (_u *FleetDeliveryUpdate) AddDriverID(v int) *FleetDeliveryUpdate {
	_u.mutation.AddDriverID(v)
	return _u
}

// ClearDriverID clears the value of the "driver_id" field.
func (_u *FleetDeliveryUpdate) ClearDriverID() *FleetDeliveryUpdate {
	_u.mutation.ClearDriverID()
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *FleetDeliveryUpdate) SetVehicleID(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetVehicleID()
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableVehicleID(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// AddVehicleID adds value to the "vehicle_id" field.
func (_u *FleetDeliveryUpdate) AddVehicleID(v int) *FleetDeliveryUpdate {
	_u.mutation.AddVehicleID(v)
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *FleetDeliveryUpdate) ClearVehicleID() *FleetDeliveryUpdate {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *FleetDeliveryUpdate) SetAssignedBy(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetAssignedBy()
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableAssignedBy(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// AddAssignedBy adds value to the "assigned_by" field.
func (_u *FleetDeliveryUpdate) AddAssignedBy(v int) *FleetDeliveryUpdate {
	_u.mutation.AddAssignedBy(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FleetDeliveryUpdate) SetStatus(v string) *FleetDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableStatus(v *string) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *FleetDeliveryUpdate) SetVersion(v int) *FleetDeliveryUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableVersion(v *int) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *FleetDeliveryUpdate) AddVersion(v int) *FleetDeliveryUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FleetDeliveryUpdate) SetDeletedAt(v time.Time) *FleetDeliveryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableDeletedAt(v *time.Time) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FleetDeliveryUpdate) ClearDeletedAt() *FleetDeliveryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FleetDeliveryUpdate) SetCreatedAt(v time.Time) *FleetDeliveryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FleetDeliveryUpdate) SetNillableCreatedAt(v *time.Time) *FleetDeliveryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FleetDeliveryUpdate) SetUpdatedAt(v time.Time) *FleetDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FleetDeliveryMutation object of the builder.
func (_u *FleetDeliveryUpdate) Mutation() *FleetDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FleetDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FleetDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FleetDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FleetDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FleetDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fleetdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FleetDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(fleetdelivery.Table, fleetdelivery.Columns, sqlgraph.NewFieldSpec(fleetdelivery.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(fleetdelivery.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(fleetdelivery.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(fleetdelivery.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(fleetdelivery.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(fleetdelivery.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(fleetdelivery.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRouteID(); ok {
		_spec.AddField(fleetdelivery.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DriverID(); ok {
		_spec.SetField(fleetdelivery.FieldDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDriverID(); ok {
		_spec.AddField(fleetdelivery.FieldDriverID, field.TypeInt, value)
	}
	if _u.mutation.DriverIDCleared() {
		_spec.ClearField(fleetdelivery.FieldDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.VehicleID(); ok {
		_spec.SetField(fleetdelivery.FieldVehicleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVehicleID(); ok {
		_spec.AddField(fleetdelivery.FieldVehicleID, field.TypeInt, value)
	}
	if _u.mutation.VehicleIDCleared() {
		_spec.ClearField(fleetdelivery.FieldVehicleID, field.TypeInt)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(fleetdelivery.FieldAssignedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAssignedBy(); ok {
		_spec.AddField(fleetdelivery.FieldAssignedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fleetdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(fleetdelivery.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(fleetdelivery.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fleetdelivery.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fleetdelivery.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fleetdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FleetDeliveryUpdateOne is the builder for updating a single FleetDelivery entity.
type FleetDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FleetDeliveryMutation
}

// SetCompanyID sets the "company_id" field.
func (_u *FleetDeliveryUpdateOne) SetCompanyID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableCompanyID(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *FleetDeliveryUpdateOne) AddCompanyID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *FleetDeliveryUpdateOne) SetDepartmentID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableDepartmentID(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *FleetDeliveryUpdateOne) AddDepartmentID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *FleetDeliveryUpdateOne) ClearDepartmentID() *FleetDeliveryUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *FleetDeliveryUpdateOne) SetRouteID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetRouteID()
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableRouteID(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// AddRouteID adds value to the "route_id" field.
func (_u *FleetDeliveryUpdateOne) AddRouteID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddRouteID(v)
	return _u
}

// SetDriverID sets the "driver_id" field.
func (_u *FleetDeliveryUpdateOne) SetDriverID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetDriverID()
	_u.mutation.SetDriverID(v)
	return _u
}

// SetNillableDriverID sets the "driver_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableDriverID(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetDriverID(*v)
	}
	return _u
}

// AddDriverID adds value to the "driver_id" field.
func (_u *FleetDeliveryUpdateOne) AddDriverID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddDriverID(v)
	return _u
}

// ClearDriverID clears the value of the "driver_id" field.
func (_u *FleetDeliveryUpdateOne) ClearDriverID() *FleetDeliveryUpdateOne {
	_u.mutation.ClearDriverID()
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *FleetDeliveryUpdateOne) SetVehicleID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetVehicleID()
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableVehicleID(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// AddVehicleID adds value to the "vehicle_id" field.
func (_u *FleetDeliveryUpdateOne) AddVehicleID(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddVehicleID(v)
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *FleetDeliveryUpdateOne) ClearVehicleID() *FleetDeliveryUpdateOne {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *FleetDeliveryUpdateOne) SetAssignedBy(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetAssignedBy()
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableAssignedBy(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// AddAssignedBy adds value to the "assigned_by" field.
func (_u *FleetDeliveryUpdateOne) AddAssignedBy(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddAssignedBy(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FleetDeliveryUpdateOne) SetStatus(v string) *FleetDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableStatus(v *string) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *FleetDeliveryUpdateOne) SetVersion(v int) *FleetDeliveryUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableVersion(v *int) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *FleetDeliveryUpdateOne) AddVersion(v int) *FleetDeliveryUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FleetDeliveryUpdateOne) SetDeletedAt(v time.Time) *FleetDeliveryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableDeletedAt(v *time.Time) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FleetDeliveryUpdateOne) ClearDeletedAt() *FleetDeliveryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FleetDeliveryUpdateOne) SetCreatedAt(v time.Time) *FleetDeliveryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FleetDeliveryUpdateOne) SetNillableCreatedAt(v *time.Time) *FleetDeliveryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FleetDeliveryUpdateOne) SetUpdatedAt(v time.Time) *FleetDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FleetDeliveryMutation object of the builder.
func (_u *FleetDeliveryUpdateOne) Mutation() *FleetDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the FleetDeliveryUpdate builder.
func (_u *FleetDeliveryUpdateOne) Where(ps ...predicate.FleetDelivery) *FleetDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FleetDeliveryUpdateOne) Select(field string, fields ...string) *FleetDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FleetDelivery entity.
func (_u *FleetDeliveryUpdateOne) Save(ctx context.Context) (*FleetDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FleetDeliveryUpdateOne) SaveX(ctx context.Context) *FleetDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FleetDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FleetDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FleetDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fleetdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FleetDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *FleetDelivery, err error) {
	_spec := sqlgraph.NewUpdateSpec(fleetdelivery.Table, fleetdelivery.Columns, sqlgraph.NewFieldSpec(fleetdelivery.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FleetDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fleetdelivery.FieldID)
		for _, f := range fields {
			if !fleetdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fleetdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(fleetdelivery.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(fleetdelivery.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(fleetdelivery.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(fleetdelivery.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(fleetdelivery.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(fleetdelivery.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRouteID(); ok {
		_spec.AddField(fleetdelivery.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DriverID(); ok {
		_spec.SetField(fleetdelivery.FieldDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDriverID(); ok {
		_spec.AddField(fleetdelivery.FieldDriverID, field.TypeInt, value)
	}
	if _u.mutation.DriverIDCleared() {
		_spec.ClearField(fleetdelivery.FieldDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.VehicleID(); ok {
		_spec.SetField(fleetdelivery.FieldVehicleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVehicleID(); ok {
		_spec.AddField(fleetdelivery.FieldVehicleID, field.TypeInt, value)
	}
	if _u.mutation.VehicleIDCleared() {
		_spec.ClearField(fleetdelivery.FieldVehicleID, field.TypeInt)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(fleetdelivery.FieldAssignedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAssignedBy(); ok {
		_spec.AddField(fleetdelivery.FieldAssignedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fleetdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(fleetdelivery.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(fleetdelivery.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fleetdelivery.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fleetdelivery.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FleetDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fleetdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
