// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/fleetdelivery"
)

// FleetDeliveryCreate is the builder for creating a FleetDelivery entity.
type FleetDeliveryCreate struct {
	config
	mutation *FleetDeliveryMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (_c *FleetDeliveryCreate) SetCompanyID(v int) *FleetDeliveryCreate {
	_c.mutation.SetCompanyID(v)
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *FleetDeliveryCreate) SetDepartmentID(v int) *FleetDeliveryCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableDepartmentID(v *int) *FleetDeliveryCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetRouteID sets the "route_id" field.
func (_c *FleetDeliveryCreate) SetRouteID(v int) *FleetDeliveryCreate {
	_c.mutation.SetRouteID(v)
	return _c
}

// SetDriverID sets the "driver_id" field.
func (_c *FleetDeliveryCreate) SetDriverID(v int) *FleetDeliveryCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetNillableDriverID sets the "driver_id" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableDriverID(v *int) *FleetDeliveryCreate {
	if v != nil {
		_c.SetDriverID(*v)
	}
	return _c
}

// SetVehicleID sets the "vehicle_id" field.
func (_c *FleetDeliveryCreate) SetVehicleID(v int) *FleetDeliveryCreate {
	_c.mutation.SetVehicleID(v)
	return _c
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableVehicleID(v *int) *FleetDeliveryCreate {
	if v != nil {
		_c.SetVehicleID(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *FleetDeliveryCreate) SetAssignedBy(v int) *FleetDeliveryCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *FleetDeliveryCreate) SetStatus(v string) *FleetDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableStatus(v *string) *FleetDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *FleetDeliveryCreate) SetVersion(v int) *FleetDeliveryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableVersion(v *int) *FleetDeliveryCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *FleetDeliveryCreate) SetDeletedAt(v time.Time) *FleetDeliveryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableDeletedAt(v *time.Time) *FleetDeliveryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FleetDeliveryCreate) SetCreatedAt(v time.Time) *FleetDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableCreatedAt(v *time.Time) *FleetDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FleetDeliveryCreate) SetUpdatedAt(v time.Time) *FleetDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FleetDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *FleetDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the FleetDeliveryMutation object of the builder.
func (_c *FleetDeliveryCreate) Mutation() *FleetDeliveryMutation {
	return _c.mutation
}

// Save creates the FleetDelivery in the database.
func (_c *FleetDeliveryCreate) Save(ctx context.Context) (*FleetDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FleetDeliveryCreate) SaveX(ctx context.Context) *FleetDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FleetDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FleetDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FleetDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := fleetdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := fleetdelivery.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := fleetdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := fleetdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FleetDeliveryCreate) check() error {
	if _, ok := _c.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "FleetDelivery.company_id"`)}
	}
	if _, ok := _c.mutation.RouteID(); !ok {
		return &ValidationError{Name: "route_id", err: errors.New(`ent: missing required field "FleetDelivery.route_id"`)}
	}
	if _, ok := _c.mutation.AssignedBy(); !ok {
		return &ValidationError{Name: "assigned_by", err: errors.New(`ent: missing required field "FleetDelivery.assigned_by"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FleetDelivery.status"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "FleetDelivery.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FleetDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FleetDelivery.updated_at"`)}
	}
	return nil
}

func (_c *FleetDeliveryCreate) sqlSave(ctx context.Context) (*FleetDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FleetDeliveryCreate) createSpec() (*FleetDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &FleetDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fleetdelivery.Table, sqlgraph.NewFieldSpec(fleetdelivery.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CompanyID(); ok {
		_spec.SetField(fleetdelivery.FieldCompanyID, field.TypeInt, value)
		_node.CompanyID = value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(fleetdelivery.FieldDepartmentID, field.TypeInt, value)
		_node.DepartmentID = &value
	}
	if value, ok := _c.mutation.RouteID(); ok {
		_spec.SetField(fleetdelivery.FieldRouteID, field.TypeInt, value)
		_node.RouteID = value
	}
	if value, ok := _c.mutation.DriverID(); ok {
		_spec.SetField(fleetdelivery.FieldDriverID, field.TypeInt, value)
		_node.DriverID = &value
	}
	if value, ok := _c.mutation.VehicleID(); ok {
		_spec.SetField(fleetdelivery.FieldVehicleID, field.TypeInt, value)
		_node.VehicleID = &value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(fleetdelivery.FieldAssignedBy, field.TypeInt, value)
		_node.AssignedBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(fleetdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(fleetdelivery.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(fleetdelivery.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fleetdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FleetDeliveryCreateBulk is the builder for creating many FleetDelivery entities in bulk.
type FleetDeliveryCreateBulk struct {
	config
	err      error
	builders []*FleetDeliveryCreate
}

// Save creates the FleetDelivery entities in the database.
func (_c *FleetDeliveryCreateBulk) Save(ctx context.Context) ([]*FleetDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FleetDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FleetDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FleetDeliveryCreateBulk) SaveX(ctx context.Context) []*FleetDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FleetDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FleetDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
