// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/ordercounter"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// OrderCounterDelete is the builder for deleting a OrderCounter entity.
type OrderCounterDelete struct {
	config
	hooks    []Hook
	mutation *OrderCounterMutation
}

// Where appends a list predicates to the OrderCounterDelete builder.
func (_d *OrderCounterDelete) Where(ps ...predicate.OrderCounter) *OrderCounterDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrderCounterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderCounterDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrderCounterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ordercounter.Table, sqlgraph.NewFieldSpec(ordercounter.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrderCounterDeleteOne is the builder for deleting a single OrderCounter entity.
type OrderCounterDeleteOne struct {
	_d *OrderCounterDelete
}

// Where appends a list predicates to the OrderCounterDelete builder.
func (_d *OrderCounterDeleteOne) Where(ps ...predicate.OrderCounter) *OrderCounterDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrderCounterDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ordercounter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderCounterDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
