// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
	"github.com/salesorder/sales-order-1.0/backend/ent/printlog"
)

// PrintLogUpdate is the builder for updating PrintLog entities.
type PrintLogUpdate struct {
	config
	hooks    []Hook
	mutation *PrintLogMutation
}

// Where appends a list predicates to the PrintLogUpdate builder.
func (_u *PrintLogUpdate) Where(ps ...predicate.PrintLog) *PrintLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *PrintLogUpdate) SetCompanyID(v int) *PrintLogUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableCompanyID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *PrintLogUpdate) AddCompanyID(v int) *PrintLogUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *PrintLogUpdate) SetDepartmentID(v int) *PrintLogUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableDepartmentID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *PrintLogUpdate) AddDepartmentID(v int) *PrintLogUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// SetDocumentType sets the "document_type" field.
func (_u *PrintLogUpdate) SetDocumentType(v string) *PrintLogUpdate {
	_u.mutation.SetDocumentType(v)
	return _u
}

// SetNillableDocumentType sets the "document_type" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableDocumentType(v *string) *PrintLogUpdate {
	if v != nil {
		_u.SetDocumentType(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *PrintLogUpdate) SetRouteID(v int) *PrintLogUpdate {
	_u.mutation.ResetRouteID()
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableRouteID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// AddRouteID adds value to the "route_id" field.
func (_u *PrintLogUpdate) AddRouteID(v int) *PrintLogUpdate {
	_u.mutation.AddRouteID(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *PrintLogUpdate) SetCustomerID(v int) *PrintLogUpdate {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableCustomerID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *PrintLogUpdate) AddCustomerID(v int) *PrintLogUpdate {
	_u.mutation.AddCustomerID(v)
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *PrintLogUpdate) ClearCustomerID() *PrintLogUpdate {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *PrintLogUpdate) SetWarehouseID(v int) *PrintLogUpdate {
	_u.mutation.ResetWarehouseID()
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableWarehouseID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// AddWarehouseID adds value to the "warehouse_id" field.
func (_u *PrintLogUpdate) AddWarehouseID(v int) *PrintLogUpdate {
	_u.mutation.AddWarehouseID(v)
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *PrintLogUpdate) ClearWarehouseID() *PrintLogUpdate {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *PrintLogUpdate) SetTargetDate(v time.Time) *PrintLogUpdate {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableTargetDate(v *time.Time) *PrintLogUpdate {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetIsReprint sets the "is_reprint" field.
func (_u *PrintLogUpdate) SetIsReprint(v bool) *PrintLogUpdate {
	_u.mutation.SetIsReprint(v)
	return _u
}

// SetNillableIsReprint sets the "is_reprint" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableIsReprint(v *bool) *PrintLogUpdate {
	if v != nil {
		_u.SetIsReprint(*v)
	}
	return _u
}

// SetReprintReason sets the "reprint_reason" field.
func (_u *PrintLogUpdate) SetReprintReason(v string) *PrintLogUpdate {
	_u.mutation.SetReprintReason(v)
	return _u
}

// SetNillableReprintReason sets the "reprint_reason" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableReprintReason(v *string) *PrintLogUpdate {
	if v != nil {
		_u.SetReprintReason(*v)
	}
	return _u
}

// ClearReprintReason clears the value of the "reprint_reason" field.
func (_u *PrintLogUpdate) ClearReprintReason() *PrintLogUpdate {
	_u.mutation.ClearReprintReason()
	return _u
}

// SetPrintedBy sets the "printed_by" field.
func (_u *PrintLogUpdate) SetPrintedBy(v int) *PrintLogUpdate {
	_u.mutation.ResetPrintedBy()
	_u.mutation.SetPrintedBy(v)
	return _u
}

// SetNillablePrintedBy sets the "printed_by" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillablePrintedBy(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetPrintedBy(*v)
	}
	return _u
}

// AddPrintedBy adds value to the "printed_by" field.
func (_u *PrintLogUpdate) AddPrintedBy(v int) *PrintLogUpdate {
	_u.mutation.AddPrintedBy(v)
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PrintLogUpdate) SetPrintedAt(v time.Time) *PrintLogUpdate {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillablePrintedAt(v *time.Time) *PrintLogUpdate {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// SetFileAssetID sets the "file_asset_id" field.
func (_u *PrintLogUpdate) SetFileAssetID(v int) *PrintLogUpdate {
	_u.mutation.ResetFileAssetID()
	_u.mutation.SetFileAssetID(v)
	return _u
}

// SetNillableFileAssetID sets the "file_asset_id" field if the given value is not nil.
func (_u *PrintLogUpdate) SetNillableFileAssetID(v *int) *PrintLogUpdate {
	if v != nil {
		_u.SetFileAssetID(*v)
	}
	return _u
}

// AddFileAssetID adds value to the "file_asset_id" field.
func (_u *PrintLogUpdate) AddFileAssetID(v int) *PrintLogUpdate {
	_u.mutation.AddFileAssetID(v)
	return _u
}

// Mutation returns the PrintLogMutation object of the builder.
func (_u *PrintLogUpdate) Mutation() *PrintLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrintLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrintLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrintLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrintLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrintLogUpdate) check() error {
	if v, ok := _u.mutation.DocumentType(); ok {
		if err := printlog.DocumentTypeValidator(v); err != nil {
			return &ValidationError{Name: "document_type", err: fmt.Errorf(`ent: validator failed for field "PrintLog.document_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PrintLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(printlog.Table, printlog.Columns, sqlgraph.NewFieldSpec(printlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(printlog.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(printlog.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(printlog.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(printlog.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DocumentType(); ok {
		_spec.SetField(printlog.FieldDocumentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(printlog.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRouteID(); ok {
		_spec.AddField(printlog.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(printlog.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(printlog.FieldCustomerID, field.TypeInt, value)
	}
	if _u.mutation.CustomerIDCleared() {
		_spec.ClearField(printlog.FieldCustomerID, field.TypeInt)
	}
	if value, ok := _u.mutation.WarehouseID(); ok {
		_spec.SetField(printlog.FieldWarehouseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWarehouseID(); ok {
		_spec.AddField(printlog.FieldWarehouseID, field.TypeInt, value)
	}
	if _u.mutation.WarehouseIDCleared() {
		_spec.ClearField(printlog.FieldWarehouseID, field.TypeInt)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(printlog.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsReprint(); ok {
		_spec.SetField(printlog.FieldIsReprint, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReprintReason(); ok {
		_spec.SetField(printlog.FieldReprintReason, field.TypeString, value)
	}
	if _u.mutation.ReprintReasonCleared() {
		_spec.ClearField(printlog.FieldReprintReason, field.TypeString)
	}
	if value, ok := _u.mutation.PrintedBy(); ok {
		_spec.SetField(printlog.FieldPrintedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrintedBy(); ok {
		_spec.AddField(printlog.FieldPrintedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(printlog.FieldPrintedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileAssetID(); ok {
		_spec.SetField(printlog.FieldFileAssetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileAssetID(); ok {
		_spec.AddField(printlog.FieldFileAssetID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{printlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrintLogUpdateOne is the builder for updating a single PrintLog entity.
type PrintLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrintLogMutation
}

// SetCompanyID sets the "company_id" field.
func (_u *PrintLogUpdateOne) SetCompanyID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableCompanyID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *PrintLogUpdateOne) AddCompanyID(v int) *PrintLogUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *PrintLogUpdateOne) SetDepartmentID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableDepartmentID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *PrintLogUpdateOne) AddDepartmentID(v int) *PrintLogUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// SetDocumentType sets the "document_type" field.
func (_u *PrintLogUpdateOne) SetDocumentType(v string) *PrintLogUpdateOne {
	_u.mutation.SetDocumentType(v)
	return _u
}

// SetNillableDocumentType sets the "document_type" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableDocumentType(v *string) *PrintLogUpdateOne {
	if v != nil {
		_u.SetDocumentType(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *PrintLogUpdateOne) SetRouteID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetRouteID()
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableRouteID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// AddRouteID adds value to the "route_id" field.
func (_u *PrintLogUpdateOne) AddRouteID(v int) *PrintLogUpdateOne {
	_u.mutation.AddRouteID(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *PrintLogUpdateOne) SetCustomerID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableCustomerID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *PrintLogUpdateOne) AddCustomerID(v int) *PrintLogUpdateOne {
	_u.mutation.AddCustomerID(v)
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *PrintLogUpdateOne) ClearCustomerID() *PrintLogUpdateOne {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *PrintLogUpdateOne) SetWarehouseID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetWarehouseID()
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableWarehouseID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// AddWarehouseID adds value to the "warehouse_id" field.
func (_u *PrintLogUpdateOne) AddWarehouseID(v int) *PrintLogUpdateOne {
	_u.mutation.AddWarehouseID(v)
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *PrintLogUpdateOne) ClearWarehouseID() *PrintLogUpdateOne {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *PrintLogUpdateOne) SetTargetDate(v time.Time) *PrintLogUpdateOne {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableTargetDate(v *time.Time) *PrintLogUpdateOne {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetIsReprint sets the "is_reprint" field.
func (_u *PrintLogUpdateOne) SetIsReprint(v bool) *PrintLogUpdateOne {
	_u.mutation.SetIsReprint(v)
	return _u
}

// SetNillableIsReprint sets the "is_reprint" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableIsReprint(v *bool) *PrintLogUpdateOne {
	if v != nil {
		_u.SetIsReprint(*v)
	}
	return _u
}

// SetReprintReason sets the "reprint_reason" field.
func (_u *PrintLogUpdateOne) SetReprintReason(v string) *PrintLogUpdateOne {
	_u.mutation.SetReprintReason(v)
	return _u
}

// SetNillableReprintReason sets the "reprint_reason" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableReprintReason(v *string) *PrintLogUpdateOne {
	if v != nil {
		_u.SetReprintReason(*v)
	}
	return _u
}

// ClearReprintReason clears the value of the "reprint_reason" field.
func (_u *PrintLogUpdateOne) ClearReprintReason() *PrintLogUpdateOne {
	_u.mutation.ClearReprintReason()
	return _u
}

// SetPrintedBy sets the "printed_by" field.
func (_u *PrintLogUpdateOne) SetPrintedBy(v int) *PrintLogUpdateOne {
	_u.mutation.ResetPrintedBy()
	_u.mutation.SetPrintedBy(v)
	return _u
}

// SetNillablePrintedBy sets the "printed_by" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillablePrintedBy(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetPrintedBy(*v)
	}
	return _u
}

// AddPrintedBy adds value to the "printed_by" field.
func (_u *PrintLogUpdateOne) AddPrintedBy(v int) *PrintLogUpdateOne {
	_u.mutation.AddPrintedBy(v)
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PrintLogUpdateOne) SetPrintedAt(v time.Time) *PrintLogUpdateOne {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillablePrintedAt(v *time.Time) *PrintLogUpdateOne {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// SetFileAssetID sets the "file_asset_id" field.
func (_u *PrintLogUpdateOne) SetFileAssetID(v int) *PrintLogUpdateOne {
	_u.mutation.ResetFileAssetID()
	_u.mutation.SetFileAssetID(v)
	return _u
}

// SetNillableFileAssetID sets the "file_asset_id" field if the given value is not nil.
func (_u *PrintLogUpdateOne) SetNillableFileAssetID(v *int) *PrintLogUpdateOne {
	if v != nil {
		_u.SetFileAssetID(*v)
	}
	return _u
}

// AddFileAssetID adds value to the "file_asset_id" field.
func (_u *PrintLogUpdateOne) AddFileAssetID(v int) *PrintLogUpdateOne {
	_u.mutation.AddFileAssetID(v)
	return _u
}

// Mutation returns the PrintLogMutation object of the builder.
func (_u *PrintLogUpdateOne) Mutation() *PrintLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the PrintLogUpdate builder.
func (_u *PrintLogUpdateOne) Where(ps ...predicate.PrintLog) *PrintLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrintLogUpdateOne) Select(field string, fields ...string) *PrintLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PrintLog entity.
func (_u *PrintLogUpdateOne) Save(ctx context.Context) (*PrintLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrintLogUpdateOne) SaveX(ctx context.Context) *PrintLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrintLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrintLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrintLogUpdateOne) check() error {
	if v, ok := _u.mutation.DocumentType(); ok {
		if err := printlog.DocumentTypeValidator(v); err != nil {
			return &ValidationError{Name: "document_type", err: fmt.Errorf(`ent: validator failed for field "PrintLog.document_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PrintLogUpdateOne) sqlSave(ctx context.Context) (_node *PrintLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(printlog.Table, printlog.Columns, sqlgraph.NewFieldSpec(printlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PrintLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, printlog.FieldID)
		for _, f := range fields {
			if !printlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != printlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(printlog.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(printlog.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(printlog.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(printlog.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DocumentType(); ok {
		_spec.SetField(printlog.FieldDocumentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(printlog.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRouteID(); ok {
		_spec.AddField(printlog.FieldRouteID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(printlog.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(printlog.FieldCustomerID, field.TypeInt, value)
	}
	if _u.mutation.CustomerIDCleared() {
		_spec.ClearField(printlog.FieldCustomerID, field.TypeInt)
	}
	if value, ok := _u.mutation.WarehouseID(); ok {
		_spec.SetField(printlog.FieldWarehouseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWarehouseID(); ok {
		_spec.AddField(printlog.FieldWarehouseID, field.TypeInt, value)
	}
	if _u.mutation.WarehouseIDCleared() {
		_spec.ClearField(printlog.FieldWarehouseID, field.TypeInt)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(printlog.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsReprint(); ok {
		_spec.SetField(printlog.FieldIsReprint, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReprintReason(); ok {
		_spec.SetField(printlog.FieldReprintReason, field.TypeString, value)
	}
	if _u.mutation.ReprintReasonCleared() {
		_spec.ClearField(printlog.FieldReprintReason, field.TypeString)
	}
	if value, ok := _u.mutation.PrintedBy(); ok {
		_spec.SetField(printlog.FieldPrintedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrintedBy(); ok {
		_spec.AddField(printlog.FieldPrintedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(printlog.FieldPrintedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileAssetID(); ok {
		_spec.SetField(printlog.FieldFileAssetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileAssetID(); ok {
		_spec.AddField(printlog.FieldFileAssetID, field.TypeInt, value)
	}
	_node = &PrintLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{printlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
