// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
	"github.com/salesorder/sales-order-1.0/backend/ent/processingspec"
)

// ProcessingSpecUpdate is the builder for updating ProcessingSpec entities.
type ProcessingSpecUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessingSpecMutation
}

// Where appends a list predicates to the ProcessingSpecUpdate builder.
func (_u *ProcessingSpecUpdate) Where(ps ...predicate.ProcessingSpec) *ProcessingSpecUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *ProcessingSpecUpdate) SetCompanyID(v int) *ProcessingSpecUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableCompanyID(v *int) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *ProcessingSpecUpdate) AddCompanyID(v int) *ProcessingSpecUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ProcessingSpecUpdate) SetDepartmentID(v int) *ProcessingSpecUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableDepartmentID(v *int) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ProcessingSpecUpdate) AddDepartmentID(v int) *ProcessingSpecUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ProcessingSpecUpdate) ClearDepartmentID() *ProcessingSpecUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCode sets the "code" field.
func (_u *ProcessingSpecUpdate) SetCode(v string) *ProcessingSpecUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableCode(v *string) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProcessingSpecUpdate) SetName(v string) *ProcessingSpecUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableName(v *string) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ProcessingSpecUpdate) SetKind(v string) *ProcessingSpecUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableKind(v *string) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAppliesToProcessing sets the "applies_to_processing" field.
func (_u *ProcessingSpecUpdate) SetAppliesToProcessing(v bool) *ProcessingSpecUpdate {
	_u.mutation.SetAppliesToProcessing(v)
	return _u
}

// SetNillableAppliesToProcessing sets the "applies_to_processing" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableAppliesToProcessing(v *bool) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetAppliesToProcessing(*v)
	}
	return _u
}

// SetAppliesToPicking sets the "applies_to_picking" field.
func (_u *ProcessingSpecUpdate) SetAppliesToPicking(v bool) *ProcessingSpecUpdate {
	_u.mutation.SetAppliesToPicking(v)
	return _u
}

// SetNillableAppliesToPicking sets the "applies_to_picking" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableAppliesToPicking(v *bool) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetAppliesToPicking(*v)
	}
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *ProcessingSpecUpdate) SetAttributes(v map[string]interface{}) *ProcessingSpecUpdate {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *ProcessingSpecUpdate) ClearAttributes() *ProcessingSpecUpdate {
	_u.mutation.ClearAttributes()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProcessingSpecUpdate) SetSortOrder(v int) *ProcessingSpecUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableSortOrder(v *int) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProcessingSpecUpdate) AddSortOrder(v int) *ProcessingSpecUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProcessingSpecUpdate) SetIsActive(v bool) *ProcessingSpecUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableIsActive(v *bool) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProcessingSpecUpdate) SetCreatedBy(v int) *ProcessingSpecUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableCreatedBy(v *int) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProcessingSpecUpdate) AddCreatedBy(v int) *ProcessingSpecUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProcessingSpecUpdate) ClearCreatedBy() *ProcessingSpecUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProcessingSpecUpdate) SetUpdatedBy(v int) *ProcessingSpecUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableUpdatedBy(v *int) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProcessingSpecUpdate) AddUpdatedBy(v int) *ProcessingSpecUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProcessingSpecUpdate) ClearUpdatedBy() *ProcessingSpecUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProcessingSpecUpdate) SetCreatedAt(v time.Time) *ProcessingSpecUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableCreatedAt(v *time.Time) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessingSpecUpdate) SetUpdatedAt(v time.Time) *ProcessingSpecUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProcessingSpecUpdate) SetDeletedAt(v time.Time) *ProcessingSpecUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProcessingSpecUpdate) SetNillableDeletedAt(v *time.Time) *ProcessingSpecUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProcessingSpecUpdate) ClearDeletedAt() *ProcessingSpecUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ProcessingSpecMutation object of the builder.
func (_u *ProcessingSpecUpdate) Mutation() *ProcessingSpecMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessingSpecUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessingSpecUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessingSpecUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessingSpecUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessingSpecUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := processingspec.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessingSpecUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := processingspec.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ProcessingSpec.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := processingspec.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProcessingSpec.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessingSpecUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processingspec.Table, processingspec.Columns, sqlgraph.NewFieldSpec(processingspec.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(processingspec.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(processingspec.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(processingspec.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(processingspec.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(processingspec.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(processingspec.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(processingspec.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(processingspec.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliesToProcessing(); ok {
		_spec.SetField(processingspec.FieldAppliesToProcessing, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AppliesToPicking(); ok {
		_spec.SetField(processingspec.FieldAppliesToPicking, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(processingspec.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(processingspec.FieldAttributes, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(processingspec.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(processingspec.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(processingspec.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(processingspec.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(processingspec.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(processingspec.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(processingspec.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(processingspec.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(processingspec.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(processingspec.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(processingspec.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(processingspec.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(processingspec.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processingspec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessingSpecUpdateOne is the builder for updating a single ProcessingSpec entity.
type ProcessingSpecUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessingSpecMutation
}

// SetCompanyID sets the "company_id" field.
func (_u *ProcessingSpecUpdateOne) SetCompanyID(v int) *ProcessingSpecUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableCompanyID(v *int) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *ProcessingSpecUpdateOne) AddCompanyID(v int) *ProcessingSpecUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ProcessingSpecUpdateOne) SetDepartmentID(v int) *ProcessingSpecUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableDepartmentID(v *int) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ProcessingSpecUpdateOne) AddDepartmentID(v int) *ProcessingSpecUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ProcessingSpecUpdateOne) ClearDepartmentID() *ProcessingSpecUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCode sets the "code" field.
func (_u *ProcessingSpecUpdateOne) SetCode(v string) *ProcessingSpecUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableCode(v *string) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProcessingSpecUpdateOne) SetName(v string) *ProcessingSpecUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableName(v *string) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ProcessingSpecUpdateOne) SetKind(v string) *ProcessingSpecUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableKind(v *string) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAppliesToProcessing sets the "applies_to_processing" field.
func (_u *ProcessingSpecUpdateOne) SetAppliesToProcessing(v bool) *ProcessingSpecUpdateOne {
	_u.mutation.SetAppliesToProcessing(v)
	return _u
}

// SetNillableAppliesToProcessing sets the "applies_to_processing" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableAppliesToProcessing(v *bool) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetAppliesToProcessing(*v)
	}
	return _u
}

// SetAppliesToPicking sets the "applies_to_picking" field.
func (_u *ProcessingSpecUpdateOne) SetAppliesToPicking(v bool) *ProcessingSpecUpdateOne {
	_u.mutation.SetAppliesToPicking(v)
	return _u
}

// SetNillableAppliesToPicking sets the "applies_to_picking" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableAppliesToPicking(v *bool) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetAppliesToPicking(*v)
	}
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *ProcessingSpecUpdateOne) SetAttributes(v map[string]interface{}) *ProcessingSpecUpdateOne {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *ProcessingSpecUpdateOne) ClearAttributes() *ProcessingSpecUpdateOne {
	_u.mutation.ClearAttributes()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProcessingSpecUpdateOne) SetSortOrder(v int) *ProcessingSpecUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableSortOrder(v *int) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProcessingSpecUpdateOne) AddSortOrder(v int) *ProcessingSpecUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProcessingSpecUpdateOne) SetIsActive(v bool) *ProcessingSpecUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableIsActive(v *bool) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProcessingSpecUpdateOne) SetCreatedBy(v int) *ProcessingSpecUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableCreatedBy(v *int) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProcessingSpecUpdateOne) AddCreatedBy(v int) *ProcessingSpecUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProcessingSpecUpdateOne) ClearCreatedBy() *ProcessingSpecUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProcessingSpecUpdateOne) SetUpdatedBy(v int) *ProcessingSpecUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableUpdatedBy(v *int) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProcessingSpecUpdateOne) AddUpdatedBy(v int) *ProcessingSpecUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProcessingSpecUpdateOne) ClearUpdatedBy() *ProcessingSpecUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProcessingSpecUpdateOne) SetCreatedAt(v time.Time) *ProcessingSpecUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableCreatedAt(v *time.Time) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessingSpecUpdateOne) SetUpdatedAt(v time.Time) *ProcessingSpecUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProcessingSpecUpdateOne) SetDeletedAt(v time.Time) *ProcessingSpecUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProcessingSpecUpdateOne) SetNillableDeletedAt(v *time.Time) *ProcessingSpecUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProcessingSpecUpdateOne) ClearDeletedAt() *ProcessingSpecUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ProcessingSpecMutation object of the builder.
func (_u *ProcessingSpecUpdateOne) Mutation() *ProcessingSpecMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessingSpecUpdate builder.
func (_u *ProcessingSpecUpdateOne) Where(ps ...predicate.ProcessingSpec) *ProcessingSpecUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessingSpecUpdateOne) Select(field string, fields ...string) *ProcessingSpecUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProcessingSpec entity.
func (_u *ProcessingSpecUpdateOne) Save(ctx context.Context) (*ProcessingSpec, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessingSpecUpdateOne) SaveX(ctx context.Context) *ProcessingSpec {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessingSpecUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessingSpecUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessingSpecUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := processingspec.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessingSpecUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := processingspec.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ProcessingSpec.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := processingspec.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProcessingSpec.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessingSpecUpdateOne) sqlSave(ctx context.Context) (_node *ProcessingSpec, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processingspec.Table, processingspec.Columns, sqlgraph.NewFieldSpec(processingspec.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessingSpec.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processingspec.FieldID)
		for _, f := range fields {
			if !processingspec.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processingspec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(processingspec.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(processingspec.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(processingspec.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(processingspec.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(processingspec.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(processingspec.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(processingspec.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(processingspec.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliesToProcessing(); ok {
		_spec.SetField(processingspec.FieldAppliesToProcessing, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AppliesToPicking(); ok {
		_spec.SetField(processingspec.FieldAppliesToPicking, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(processingspec.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(processingspec.FieldAttributes, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(processingspec.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(processingspec.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(processingspec.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(processingspec.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(processingspec.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(processingspec.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(processingspec.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(processingspec.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(processingspec.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(processingspec.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(processingspec.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(processingspec.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(processingspec.FieldDeletedAt, field.TypeTime)
	}
	_node = &ProcessingSpec{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processingspec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
