// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
	"github.com/salesorder/sales-order-1.0/backend/ent/salesorderevent"
)

// SalesOrderEventDelete is the builder for deleting a SalesOrderEvent entity.
type SalesOrderEventDelete struct {
	config
	hooks    []Hook
	mutation *SalesOrderEventMutation
}

// Where appends a list predicates to the SalesOrderEventDelete builder.
func (_d *SalesOrderEventDelete) Where(ps ...predicate.SalesOrderEvent) *SalesOrderEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SalesOrderEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SalesOrderEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SalesOrderEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(salesorderevent.Table, sqlgraph.NewFieldSpec(salesorderevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SalesOrderEventDeleteOne is the builder for deleting a single SalesOrderEvent entity.
type SalesOrderEventDeleteOne struct {
	_d *SalesOrderEventDelete
}

// Where appends a list predicates to the SalesOrderEventDelete builder.
func (_d *SalesOrderEventDeleteOne) Where(ps ...predicate.SalesOrderEvent) *SalesOrderEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SalesOrderEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{salesorderevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SalesOrderEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
