// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"create", "update", "delete", "login", "logout", "print", "force_logout", "role_change", "dispatch_cancel", "void"}},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString, Nullable: true},
		{Name: "before_snapshot", Type: field.TypeJSON, Nullable: true},
		{Name: "after_snapshot", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
	}
	// CompaniesColumns holds the columns for the "companies" table.
	CompaniesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "tax_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "identifier", Type: field.TypeString},
		{Name: "public_info", Type: field.TypeJSON, Nullable: true},
		{Name: "capabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "logo_url", Type: field.TypeString, Nullable: true},
		{Name: "customer_code_prefix", Type: field.TypeString, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CompaniesTable holds the schema information for the "companies" table.
	CompaniesTable = &schema.Table{
		Name:       "companies",
		Columns:    CompaniesColumns,
		PrimaryKey: []*schema.Column{CompaniesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "company_identifier",
				Unique:  true,
				Columns: []*schema.Column{CompaniesColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
		},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "customer_code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "tax_id", Type: field.TypeString, Nullable: true},
		{Name: "payment_method_id", Type: field.TypeInt, Nullable: true},
		{Name: "settlement_method_id", Type: field.TypeInt, Nullable: true},
		{Name: "customer_type_id", Type: field.TypeInt, Nullable: true},
		{Name: "invoice_type_id", Type: field.TypeInt, Nullable: true},
		{Name: "default_sales_rep_id", Type: field.TypeInt, Nullable: true},
		{Name: "preferred_delivery_days", Type: field.TypeJSON},
		{Name: "promo_tag_ids", Type: field.TypeJSON},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customer_company_id_customer_code",
				Unique:  false,
				Columns: []*schema.Column{CustomersColumns[1], CustomersColumns[3]},
			},
			{
				Name:    "customer_department_id",
				Unique:  false,
				Columns: []*schema.Column{CustomersColumns[2]},
			},
			{
				Name:    "customer_default_sales_rep_id",
				Unique:  false,
				Columns: []*schema.Column{CustomersColumns[10]},
			},
		},
	}
	// CustomerAddressesColumns holds the columns for the "customer_addresses" table.
	CustomerAddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "customer_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"shipping", "billing", "other"}, Default: "other"},
		{Name: "recipient_name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "address_line", Type: field.TypeString},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "postal_code", Type: field.TypeString, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CustomerAddressesTable holds the schema information for the "customer_addresses" table.
	CustomerAddressesTable = &schema.Table{
		Name:       "customer_addresses",
		Columns:    CustomerAddressesColumns,
		PrimaryKey: []*schema.Column{CustomerAddressesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customeraddress_customer_id",
				Unique:  false,
				Columns: []*schema.Column{CustomerAddressesColumns[2]},
			},
			{
				Name:    "customeraddress_customer_id_type",
				Unique:  false,
				Columns: []*schema.Column{CustomerAddressesColumns[2], CustomerAddressesColumns[4]},
			},
		},
	}
	// CustomerContactsColumns holds the columns for the "customer_contacts" table.
	CustomerContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "customer_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CustomerContactsTable holds the schema information for the "customer_contacts" table.
	CustomerContactsTable = &schema.Table{
		Name:       "customer_contacts",
		Columns:    CustomerContactsColumns,
		PrimaryKey: []*schema.Column{CustomerContactsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customercontact_customer_id",
				Unique:  false,
				Columns: []*schema.Column{CustomerContactsColumns[2]},
			},
		},
	}
	// CustomerCountersColumns holds the columns for the "customer_counters" table.
	CustomerCountersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt, Unique: true},
		{Name: "next_seq", Type: field.TypeInt, Default: 1},
		{Name: "version", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CustomerCountersTable holds the schema information for the "customer_counters" table.
	CustomerCountersTable = &schema.Table{
		Name:       "customer_counters",
		Columns:    CustomerCountersColumns,
		PrimaryKey: []*schema.Column{CustomerCountersColumns[0]},
	}
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "company_departments", Type: field.TypeInt},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:       "departments",
		Columns:    DepartmentsColumns,
		PrimaryKey: []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "departments_companies_departments",
				Columns:    []*schema.Column{DepartmentsColumns[3]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MetadictsColumns holds the columns for the "metadicts" table.
	MetadictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MetadictsTable holds the schema information for the "metadicts" table.
	MetadictsTable = &schema.Table{
		Name:       "metadicts",
		Columns:    MetadictsColumns,
		PrimaryKey: []*schema.Column{MetadictsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "metadict_type_department_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{MetadictsColumns[1], MetadictsColumns[4], MetadictsColumns[6]},
			},
		},
	}
	// ProcessingSpecsColumns holds the columns for the "processing_specs" table.
	ProcessingSpecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString, Default: "other"},
		{Name: "applies_to_processing", Type: field.TypeBool, Default: false},
		{Name: "applies_to_picking", Type: field.TypeBool, Default: false},
		{Name: "attributes", Type: field.TypeJSON, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ProcessingSpecsTable holds the schema information for the "processing_specs" table.
	ProcessingSpecsTable = &schema.Table{
		Name:       "processing_specs",
		Columns:    ProcessingSpecsColumns,
		PrimaryKey: []*schema.Column{ProcessingSpecsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "processingspec_department_id_code",
				Unique:  false,
				Columns: []*schema.Column{ProcessingSpecsColumns[2], ProcessingSpecsColumns[3]},
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "category_id", Type: field.TypeInt, Nullable: true},
		{Name: "inventory_warehouse_id", Type: field.TypeInt, Nullable: true},
		{Name: "picking_warehouse_id", Type: field.TypeInt, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_department_id_code",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[2], ProductsColumns[3]},
			},
		},
	}
	// ProductCategoriesColumns holds the columns for the "product_categories" table.
	ProductCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ProductCategoriesTable holds the schema information for the "product_categories" table.
	ProductCategoriesTable = &schema.Table{
		Name:       "product_categories",
		Columns:    ProductCategoriesColumns,
		PrimaryKey: []*schema.Column{ProductCategoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "productcategory_department_id_code",
				Unique:  false,
				Columns: []*schema.Column{ProductCategoriesColumns[2], ProductCategoriesColumns[3]},
			},
		},
	}
	// ProductProcessingSpecsColumns holds the columns for the "product_processing_specs" table.
	ProductProcessingSpecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "processing_spec_id", Type: field.TypeInt},
		{Name: "attributes", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductProcessingSpecsTable holds the schema information for the "product_processing_specs" table.
	ProductProcessingSpecsTable = &schema.Table{
		Name:       "product_processing_specs",
		Columns:    ProductProcessingSpecsColumns,
		PrimaryKey: []*schema.Column{ProductProcessingSpecsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "productprocessingspec_product_id_processing_spec_id",
				Unique:  true,
				Columns: []*schema.Column{ProductProcessingSpecsColumns[1], ProductProcessingSpecsColumns[2]},
			},
		},
	}
	// ProductUnitsColumns holds the columns for the "product_units" table.
	ProductUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "unit_code", Type: field.TypeString},
		{Name: "conversion_rate", Type: field.TypeString},
		{Name: "is_base", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "size_desc", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductUnitsTable holds the schema information for the "product_units" table.
	ProductUnitsTable = &schema.Table{
		Name:       "product_units",
		Columns:    ProductUnitsColumns,
		PrimaryKey: []*schema.Column{ProductUnitsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "productunit_product_id_unit_code",
				Unique:  true,
				Columns: []*schema.Column{ProductUnitsColumns[1], ProductUnitsColumns[2]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "data_scope", Type: field.TypeEnum, Enums: []string{"all", "company", "department", "self"}, Default: "company"},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "resource", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "inverted", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "role_id", Type: field.TypeInt},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_roles_role",
				Columns:    []*schema.Column{RolePermissionsColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id_resource_action_conditions",
				Unique:  true,
				Columns: []*schema.Column{RolePermissionsColumns[6], RolePermissionsColumns[1], RolePermissionsColumns[2], RolePermissionsColumns[3]},
			},
		},
	}
	// RoutesColumns holds the columns for the "routes" table.
	RoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// RoutesTable holds the schema information for the "routes" table.
	RoutesTable = &schema.Table{
		Name:       "routes",
		Columns:    RoutesColumns,
		PrimaryKey: []*schema.Column{RoutesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "route_department_id_code",
				Unique:  false,
				Columns: []*schema.Column{RoutesColumns[2], RoutesColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "pending"}, Default: "active"},
		{Name: "role", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "employee_no", Type: field.TypeString, Nullable: true},
		{Name: "is_customer", Type: field.TypeBool, Default: false},
		{Name: "customer_id", Type: field.TypeInt, Nullable: true},
		{Name: "is_primary", Type: field.TypeBool, Default: false},
		{Name: "system_generated", Type: field.TypeBool, Default: false},
		{Name: "account_name", Type: field.TypeString, Nullable: true},
		{Name: "token_version", Type: field.TypeInt, Default: 0},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "must_change_password", Type: field.TypeBool, Default: false},
		{Name: "temp_password_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "company_users", Type: field.TypeInt},
		{Name: "department_users", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_companies_users",
				Columns:    []*schema.Column{UsersColumns[16]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "users_departments_users",
				Columns:    []*schema.Column{UsersColumns[17]},
				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WarehousesColumns holds the columns for the "warehouses" table.
	WarehousesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeInt},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// WarehousesTable holds the schema information for the "warehouses" table.
	WarehousesTable = &schema.Table{
		Name:       "warehouses",
		Columns:    WarehousesColumns,
		PrimaryKey: []*schema.Column{WarehousesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "warehouse_department_id_code",
				Unique:  false,
				Columns: []*schema.Column{WarehousesColumns[2], WarehousesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		CompaniesTable,
		CustomersTable,
		CustomerAddressesTable,
		CustomerContactsTable,
		CustomerCountersTable,
		DepartmentsTable,
		MetadictsTable,
		ProcessingSpecsTable,
		ProductsTable,
		ProductCategoriesTable,
		ProductProcessingSpecsTable,
		ProductUnitsTable,
		RolesTable,
		RolePermissionsTable,
		RoutesTable,
		UsersTable,
		WarehousesTable,
	}
)

func init() {
	DepartmentsTable.ForeignKeys[0].RefTable = CompaniesTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	UsersTable.ForeignKeys[0].RefTable = CompaniesTable
	UsersTable.ForeignKeys[1].RefTable = DepartmentsTable
}
