-- 部門軟刪除(比照公司 P2-A,2026-09-20):departments 加 deleted_at。
--
-- 背景(可達缺陷):DeleteDepartment 原以硬刪除刪列,而 audit_logs.department_id 是 FK
-- (00009 建欄、00010 補 FK → departments)。使用者相關稽核一律以「目標使用者的部門」寫
-- department_id(user_service.recordUserAudit),因此任何曾被稽核的部門成員都會留下一列
-- 指向該部門的稽核。可達路徑:
--   D 的成員 U 被做過任一次有稽核的操作(AssignRole / Deactivate / ForceLogout / UpdateUser…)
--   → 把 U 移到別的部門(前置檢查「部門仍有使用者」於是通過)→ DeleteDepartment(D)
--   → 硬刪除被 audit_logs_department_id_fkey 擋下;toConnectError 把約束錯誤映射成通用的
--   「資料違反資料庫約束…(請確認識別碼是否已被使用…)」,與真正原因(稽核 FK)無關。
-- 部門改軟刪除後,稽核列(以及倉別/路線/加工規格/產品分類/客戶等以 department_id 為 FK
-- 的列)永遠有主可依,刪除不再被 FK 阻擋,也不再需要為稽核把 department_id 清成 NULL。
--
-- 唯一性:departments 目前**沒有任何** UNIQUE 約束(00005 只有 id / name / company_departments,
-- 其餘 migration 只加 FK 與 RLS policy;ent schema 亦無 index),故不像公司 P2-A 需要把表層
-- UNIQUE 換成部分唯一索引 —— 本檔只加欄位。若日後新增部門唯一鍵,必須比照 00019 以
-- `WHERE deleted_at IS NULL` 的部分唯一索引表達,否則已刪除列會永久佔用該鍵。
--
-- 設計取捨(A/B 複審 M4,只記錄後果、不改 SQL 語意):刪除部門的唯一前置條件是「該部門沒有成員」,
-- 但被軟刪除的部門仍可能持有其他資料列的 department_id —— customers(00013)、customer_addresses /
-- customer_contacts(00015)、warehouses / routes / processing_specs / product_categories(00016)、
-- products(00017)、metadicts 的部門擴充(00011;該欄無 FK)、audit_logs(00010,這正是本波軟刪除的
-- 理由)。後果:
--   1. 這些列不會被搬遷或清除,仍在原部門歸屬下;而部門身分(deptScope/metadictScope)只在該部門
--      **有成員**時才存在(成員被調離後就沒有該部門的活身分),故它們自此對「部門」視角不可見 ——
--      只有 super / company_admin 的公司層(不含部門篩選)仍看得到。
--   2. 目前沒有回收路徑:客戶的部門只能在建立時由身分決定(CreateCustomer 的 department_id 來自
--      deptScope;UpdateCustomerRequest 沒有 department_id 欄位,客戶 RPC 也沒有改部門的方法),
--      其餘主檔的 department_id 同樣出自 deptScope/metadictScope 而非請求參數 —— 因此「把資料
--      搬到別的部門」在 API 上做不到。本波只做除役(撤銷該部門的存取身分),不做事後搬遷;
--      若日後要支援搬遷,必須另設計 RPC(並以資料列範圍授權把關),而不是回頭改這支遷移。
--
-- 影響(呼叫端必須配合,已於同一波修改):
--   1. 所有部門查詢/存在性檢查都必須排除軟刪除列(`deleted_at IS NULL`):
--      ListDepartments(含 company_id 篩選)、GetDepartment、UpdateDepartment、DeleteDepartment。
--   2. DeleteCompany 的「仍有部門」前置檢查必須忽略已軟刪除的部門,否則軟刪除的部門列會
--      讓公司永遠刪不掉(軟刪除拿走了硬刪除的隱性保護)。
--   3. validateDepartmentInCompany(user_service:CreateUser / UpdateUser / AssignRole)必須排除
--      已軟刪除的部門,否則活帳號會被掛進已刪除的部門(唯一以請求指定 department_id 的掛載路徑)。
--
-- 冪等(比照 00008/00010/00019 的 IF EXISTS 模式):對既有 DB 補欄位、對全新 DB 亦同形,
-- 重複套用為 no-op。Up/Down 對稱(加欄位 / 去欄位),兩者皆可重複套用。
-- +goose Up
-- +goose StatementBegin
ALTER TABLE departments ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE departments DROP COLUMN IF EXISTS deleted_at;
-- +goose StatementEnd
