// @generated by protoc-gen-es v2.15.0
// @generated from file salesorder/v1/returns.proto (package salesorder.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salesorder/v1/returns.proto.
 */
export declare const file_salesorder_v1_returns: GenFile;

/**
 * ReturnItemInput:單品項輸入。
 *
 * @generated from message salesorder.v1.ReturnItemInput
 */
export declare type ReturnItemInput = Message<"salesorder.v1.ReturnItemInput"> & {
  /**
   * order_item/customer_product
   *
   * @generated from field: string source_type = 1;
   */
  sourceType: string;

  /**
   * 可空(order_item 時必填)
   *
   * @generated from field: string sales_order_item_id = 2;
   */
  salesOrderItemId: string;

  /**
   * 可空(customer_product 時必填)
   *
   * @generated from field: string customer_product_id = 3;
   */
  customerProductId: string;

  /**
   * 十進位字串,正數
   *
   * @generated from field: string quantity = 4;
   */
  quantity: string;

  /**
   * 品項退貨原因
   *
   * @generated from field: string reason = 5;
   */
  reason: string;

  /**
   * 可空(≤5 張)
   *
   * @generated from field: repeated string photo_file_ids = 6;
   */
  photoFileIds: string[];
};

/**
 * Describes the message salesorder.v1.ReturnItemInput.
 * Use `create(ReturnItemInputSchema)` to create a new message.
 */
export declare const ReturnItemInputSchema: GenMessage<ReturnItemInput>;

/**
 * CreateReturnRequestRequest:發起退貨請求。
 *
 * @generated from message salesorder.v1.CreateReturnRequestRequest
 */
export declare type CreateReturnRequestRequest = Message<"salesorder.v1.CreateReturnRequestRequest"> & {
  /**
   * @generated from field: repeated salesorder.v1.ReturnItemInput items = 1;
   */
  items: ReturnItemInput[];

  /**
   * 可空
   *
   * @generated from field: string remark = 2;
   */
  remark: string;
};

/**
 * Describes the message salesorder.v1.CreateReturnRequestRequest.
 * Use `create(CreateReturnRequestRequestSchema)` to create a new message.
 */
export declare const CreateReturnRequestRequestSchema: GenMessage<CreateReturnRequestRequest>;

/**
 * CreateReturnRequestResponse:發起結果。
 *
 * @generated from message salesorder.v1.CreateReturnRequestResponse
 */
export declare type CreateReturnRequestResponse = Message<"salesorder.v1.CreateReturnRequestResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 必為 pending
   *
   * @generated from field: string status = 2;
   */
  status: string;
};

/**
 * Describes the message salesorder.v1.CreateReturnRequestResponse.
 * Use `create(CreateReturnRequestResponseSchema)` to create a new message.
 */
export declare const CreateReturnRequestResponseSchema: GenMessage<CreateReturnRequestResponse>;

/**
 * ListReturnRequestsRequest:列表請求。
 *
 * @generated from message salesorder.v1.ListReturnRequestsRequest
 */
export declare type ListReturnRequestsRequest = Message<"salesorder.v1.ListReturnRequestsRequest"> & {
  /**
   * 可空(pending/approved/rejected)
   *
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * 1-based,預設 1
   *
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * 預設 20,上限 100
   *
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;
};

/**
 * Describes the message salesorder.v1.ListReturnRequestsRequest.
 * Use `create(ListReturnRequestsRequestSchema)` to create a new message.
 */
export declare const ListReturnRequestsRequestSchema: GenMessage<ListReturnRequestsRequest>;

/**
 * ReturnRequestEntry:列表單筆。
 *
 * @generated from message salesorder.v1.ReturnRequestEntry
 */
export declare type ReturnRequestEntry = Message<"salesorder.v1.ReturnRequestEntry"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: string remark = 4;
   */
  remark: string;

  /**
   * RFC3339
   *
   * @generated from field: string created_at = 5;
   */
  createdAt: string;
};

/**
 * Describes the message salesorder.v1.ReturnRequestEntry.
 * Use `create(ReturnRequestEntrySchema)` to create a new message.
 */
export declare const ReturnRequestEntrySchema: GenMessage<ReturnRequestEntry>;

/**
 * ListReturnRequestsResponse:列表結果。
 *
 * @generated from message salesorder.v1.ListReturnRequestsResponse
 */
export declare type ListReturnRequestsResponse = Message<"salesorder.v1.ListReturnRequestsResponse"> & {
  /**
   * @generated from field: repeated salesorder.v1.ReturnRequestEntry entries = 1;
   */
  entries: ReturnRequestEntry[];

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: int32 total = 4;
   */
  total: number;
};

/**
 * Describes the message salesorder.v1.ListReturnRequestsResponse.
 * Use `create(ListReturnRequestsResponseSchema)` to create a new message.
 */
export declare const ListReturnRequestsResponseSchema: GenMessage<ListReturnRequestsResponse>;

/**
 * ReturnRequestItemView:明細單筆(含快照與照片 URL)。
 *
 * @generated from message salesorder.v1.ReturnRequestItemView
 */
export declare type ReturnRequestItemView = Message<"salesorder.v1.ReturnRequestItemView"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string source_type = 2;
   */
  sourceType: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string spec = 4;
   */
  spec: string;

  /**
   * @generated from field: string unit = 5;
   */
  unit: string;

  /**
   * @generated from field: string quantity = 6;
   */
  quantity: string;

  /**
   * @generated from field: string reason = 7;
   */
  reason: string;

  /**
   * @generated from field: repeated string photo_urls = 8;
   */
  photoUrls: string[];
};

/**
 * Describes the message salesorder.v1.ReturnRequestItemView.
 * Use `create(ReturnRequestItemViewSchema)` to create a new message.
 */
export declare const ReturnRequestItemViewSchema: GenMessage<ReturnRequestItemView>;

/**
 * GetReturnRequestRequest:單筆請求。
 *
 * @generated from message salesorder.v1.GetReturnRequestRequest
 */
export declare type GetReturnRequestRequest = Message<"salesorder.v1.GetReturnRequestRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message salesorder.v1.GetReturnRequestRequest.
 * Use `create(GetReturnRequestRequestSchema)` to create a new message.
 */
export declare const GetReturnRequestRequestSchema: GenMessage<GetReturnRequestRequest>;

/**
 * GetReturnRequestResponse:單筆結果。
 *
 * @generated from message salesorder.v1.GetReturnRequestResponse
 */
export declare type GetReturnRequestResponse = Message<"salesorder.v1.GetReturnRequestResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: string remark = 4;
   */
  remark: string;

  /**
   * @generated from field: string reject_reason = 5;
   */
  rejectReason: string;

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt: string;

  /**
   * @generated from field: repeated salesorder.v1.ReturnRequestItemView items = 7;
   */
  items: ReturnRequestItemView[];
};

/**
 * Describes the message salesorder.v1.GetReturnRequestResponse.
 * Use `create(GetReturnRequestResponseSchema)` to create a new message.
 */
export declare const GetReturnRequestResponseSchema: GenMessage<GetReturnRequestResponse>;

/**
 * ReturnService:退貨申請與審核(06 計畫 Task 4.7.2–4.7.4, D25)。
 * 發起僅客戶子帳號(主帳號一律拒絕);審核僅主責業務/dept_admin 以上;
 * 全程不修改原訂單(僅參照)。
 *
 * @generated from service salesorder.v1.ReturnService
 */
export declare const ReturnService: GenService<{
  /**
   * CreateReturnRequest:發起退貨(子帳號;雙來源並存;同交易寫申請+明細+稽核)。
   *
   * @generated from rpc salesorder.v1.ReturnService.CreateReturnRequest
   */
  createReturnRequest: {
    methodKind: "unary";
    input: typeof CreateReturnRequestRequestSchema;
    output: typeof CreateReturnRequestResponseSchema;
  },
  /**
   * ListReturnRequests:申請列表(客戶 self 限自己客戶;staff 依範圍;分頁 per_page ≤ 100)。
   *
   * @generated from rpc salesorder.v1.ReturnService.ListReturnRequests
   */
  listReturnRequests: {
    methodKind: "unary";
    input: typeof ListReturnRequestsRequestSchema;
    output: typeof ListReturnRequestsResponseSchema;
  },
  /**
   * GetReturnRequest:單筆含品項明細(照片轉下載 URL)。
   *
   * @generated from rpc salesorder.v1.ReturnService.GetReturnRequest
   */
  getReturnRequest: {
    methodKind: "unary";
    input: typeof GetReturnRequestRequestSchema;
    output: typeof GetReturnRequestResponseSchema;
  },
}>;

