// Code generated by ent, DO NOT EDIT.

package customeraddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCompanyID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCustomerID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldDepartmentID, v))
}

// RecipientName applies equality check predicate on the "recipient_name" field. It's identical to RecipientNameEQ.
func RecipientName(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldRecipientName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPhone, v))
}

// AddressLine applies equality check predicate on the "address_line" field. It's identical to AddressLineEQ.
func AddressLine(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCity, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPostalCode, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsDefault, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldDeletedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCompanyID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCustomerID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldDepartmentID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldType, vs...))
}

// RecipientNameEQ applies the EQ predicate on the "recipient_name" field.
func RecipientNameEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldRecipientName, v))
}

// RecipientNameNEQ applies the NEQ predicate on the "recipient_name" field.
func RecipientNameNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldRecipientName, v))
}

// RecipientNameIn applies the In predicate on the "recipient_name" field.
func RecipientNameIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldRecipientName, vs...))
}

// RecipientNameNotIn applies the NotIn predicate on the "recipient_name" field.
func RecipientNameNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldRecipientName, vs...))
}

// RecipientNameGT applies the GT predicate on the "recipient_name" field.
func RecipientNameGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldRecipientName, v))
}

// RecipientNameGTE applies the GTE predicate on the "recipient_name" field.
func RecipientNameGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldRecipientName, v))
}

// RecipientNameLT applies the LT predicate on the "recipient_name" field.
func RecipientNameLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldRecipientName, v))
}

// RecipientNameLTE applies the LTE predicate on the "recipient_name" field.
func RecipientNameLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldRecipientName, v))
}

// RecipientNameContains applies the Contains predicate on the "recipient_name" field.
func RecipientNameContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldRecipientName, v))
}

// RecipientNameHasPrefix applies the HasPrefix predicate on the "recipient_name" field.
func RecipientNameHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldRecipientName, v))
}

// RecipientNameHasSuffix applies the HasSuffix predicate on the "recipient_name" field.
func RecipientNameHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldRecipientName, v))
}

// RecipientNameEqualFold applies the EqualFold predicate on the "recipient_name" field.
func RecipientNameEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldRecipientName, v))
}

// RecipientNameContainsFold applies the ContainsFold predicate on the "recipient_name" field.
func RecipientNameContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldRecipientName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldPhone, v))
}

// AddressLineEQ applies the EQ predicate on the "address_line" field.
func AddressLineEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine, v))
}

// AddressLineNEQ applies the NEQ predicate on the "address_line" field.
func AddressLineNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldAddressLine, v))
}

// AddressLineIn applies the In predicate on the "address_line" field.
func AddressLineIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldAddressLine, vs...))
}

// AddressLineNotIn applies the NotIn predicate on the "address_line" field.
func AddressLineNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldAddressLine, vs...))
}

// AddressLineGT applies the GT predicate on the "address_line" field.
func AddressLineGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldAddressLine, v))
}

// AddressLineGTE applies the GTE predicate on the "address_line" field.
func AddressLineGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldAddressLine, v))
}

// AddressLineLT applies the LT predicate on the "address_line" field.
func AddressLineLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldAddressLine, v))
}

// AddressLineLTE applies the LTE predicate on the "address_line" field.
func AddressLineLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldAddressLine, v))
}

// AddressLineContains applies the Contains predicate on the "address_line" field.
func AddressLineContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldAddressLine, v))
}

// AddressLineHasPrefix applies the HasPrefix predicate on the "address_line" field.
func AddressLineHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldAddressLine, v))
}

// AddressLineHasSuffix applies the HasSuffix predicate on the "address_line" field.
func AddressLineHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldAddressLine, v))
}

// AddressLineEqualFold applies the EqualFold predicate on the "address_line" field.
func AddressLineEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldAddressLine, v))
}

// AddressLineContainsFold applies the ContainsFold predicate on the "address_line" field.
func AddressLineContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldAddressLine, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldCity, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeIsNil applies the IsNil predicate on the "postal_code" field.
func PostalCodeIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldPostalCode))
}

// PostalCodeNotNil applies the NotNil predicate on the "postal_code" field.
func PostalCodeNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldPostalCode))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldPostalCode, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldIsDefault, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldUpdatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.NotPredicates(p))
}
