// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: salesorder/v1/company.proto

package salesorderv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/salesorder/sales-order-1.0/backend/internal/proto/salesorder/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CompanyServiceName is the fully-qualified name of the CompanyService service.
	CompanyServiceName = "salesorder.v1.CompanyService"
	// DepartmentServiceName is the fully-qualified name of the DepartmentService service.
	DepartmentServiceName = "salesorder.v1.DepartmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CompanyServiceListCompaniesProcedure is the fully-qualified name of the CompanyService's
	// ListCompanies RPC.
	CompanyServiceListCompaniesProcedure = "/salesorder.v1.CompanyService/ListCompanies"
	// CompanyServiceGetCompanyProcedure is the fully-qualified name of the CompanyService's GetCompany
	// RPC.
	CompanyServiceGetCompanyProcedure = "/salesorder.v1.CompanyService/GetCompany"
	// CompanyServiceCreateCompanyProcedure is the fully-qualified name of the CompanyService's
	// CreateCompany RPC.
	CompanyServiceCreateCompanyProcedure = "/salesorder.v1.CompanyService/CreateCompany"
	// CompanyServiceUpdateCompanyProcedure is the fully-qualified name of the CompanyService's
	// UpdateCompany RPC.
	CompanyServiceUpdateCompanyProcedure = "/salesorder.v1.CompanyService/UpdateCompany"
	// CompanyServiceDeleteCompanyProcedure is the fully-qualified name of the CompanyService's
	// DeleteCompany RPC.
	CompanyServiceDeleteCompanyProcedure = "/salesorder.v1.CompanyService/DeleteCompany"
	// DepartmentServiceListDepartmentsProcedure is the fully-qualified name of the DepartmentService's
	// ListDepartments RPC.
	DepartmentServiceListDepartmentsProcedure = "/salesorder.v1.DepartmentService/ListDepartments"
	// DepartmentServiceGetDepartmentProcedure is the fully-qualified name of the DepartmentService's
	// GetDepartment RPC.
	DepartmentServiceGetDepartmentProcedure = "/salesorder.v1.DepartmentService/GetDepartment"
	// DepartmentServiceCreateDepartmentProcedure is the fully-qualified name of the DepartmentService's
	// CreateDepartment RPC.
	DepartmentServiceCreateDepartmentProcedure = "/salesorder.v1.DepartmentService/CreateDepartment"
	// DepartmentServiceUpdateDepartmentProcedure is the fully-qualified name of the DepartmentService's
	// UpdateDepartment RPC.
	DepartmentServiceUpdateDepartmentProcedure = "/salesorder.v1.DepartmentService/UpdateDepartment"
	// DepartmentServiceDeleteDepartmentProcedure is the fully-qualified name of the DepartmentService's
	// DeleteDepartment RPC.
	DepartmentServiceDeleteDepartmentProcedure = "/salesorder.v1.DepartmentService/DeleteDepartment"
)

// CompanyServiceClient is a client for the salesorder.v1.CompanyService service.
type CompanyServiceClient interface {
	// ListCompanies:分頁列出公司,可依 status / keyword(name、identifier 模糊)篩選。
	ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error)
	// GetCompany:取得單一公司。
	GetCompany(context.Context, *connect.Request[v1.GetCompanyRequest]) (*connect.Response[v1.GetCompanyResponse], error)
	// CreateCompany:建立公司。
	CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error)
	// UpdateCompany:更新公司(name、tax_id、status;identifier 建立後不可修改)。
	UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error)
	// DeleteCompany:刪除公司。
	DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error)
}

// NewCompanyServiceClient constructs a client for the salesorder.v1.CompanyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCompanyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CompanyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	companyServiceMethods := v1.File_salesorder_v1_company_proto.Services().ByName("CompanyService").Methods()
	return &companyServiceClient{
		listCompanies: connect.NewClient[v1.ListCompaniesRequest, v1.ListCompaniesResponse](
			httpClient,
			baseURL+CompanyServiceListCompaniesProcedure,
			connect.WithSchema(companyServiceMethods.ByName("ListCompanies")),
			connect.WithClientOptions(opts...),
		),
		getCompany: connect.NewClient[v1.GetCompanyRequest, v1.GetCompanyResponse](
			httpClient,
			baseURL+CompanyServiceGetCompanyProcedure,
			connect.WithSchema(companyServiceMethods.ByName("GetCompany")),
			connect.WithClientOptions(opts...),
		),
		createCompany: connect.NewClient[v1.CreateCompanyRequest, v1.CreateCompanyResponse](
			httpClient,
			baseURL+CompanyServiceCreateCompanyProcedure,
			connect.WithSchema(companyServiceMethods.ByName("CreateCompany")),
			connect.WithClientOptions(opts...),
		),
		updateCompany: connect.NewClient[v1.UpdateCompanyRequest, v1.UpdateCompanyResponse](
			httpClient,
			baseURL+CompanyServiceUpdateCompanyProcedure,
			connect.WithSchema(companyServiceMethods.ByName("UpdateCompany")),
			connect.WithClientOptions(opts...),
		),
		deleteCompany: connect.NewClient[v1.DeleteCompanyRequest, v1.DeleteCompanyResponse](
			httpClient,
			baseURL+CompanyServiceDeleteCompanyProcedure,
			connect.WithSchema(companyServiceMethods.ByName("DeleteCompany")),
			connect.WithClientOptions(opts...),
		),
	}
}

// companyServiceClient implements CompanyServiceClient.
type companyServiceClient struct {
	listCompanies *connect.Client[v1.ListCompaniesRequest, v1.ListCompaniesResponse]
	getCompany    *connect.Client[v1.GetCompanyRequest, v1.GetCompanyResponse]
	createCompany *connect.Client[v1.CreateCompanyRequest, v1.CreateCompanyResponse]
	updateCompany *connect.Client[v1.UpdateCompanyRequest, v1.UpdateCompanyResponse]
	deleteCompany *connect.Client[v1.DeleteCompanyRequest, v1.DeleteCompanyResponse]
}

// ListCompanies calls salesorder.v1.CompanyService.ListCompanies.
func (c *companyServiceClient) ListCompanies(ctx context.Context, req *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error) {
	return c.listCompanies.CallUnary(ctx, req)
}

// GetCompany calls salesorder.v1.CompanyService.GetCompany.
func (c *companyServiceClient) GetCompany(ctx context.Context, req *connect.Request[v1.GetCompanyRequest]) (*connect.Response[v1.GetCompanyResponse], error) {
	return c.getCompany.CallUnary(ctx, req)
}

// CreateCompany calls salesorder.v1.CompanyService.CreateCompany.
func (c *companyServiceClient) CreateCompany(ctx context.Context, req *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error) {
	return c.createCompany.CallUnary(ctx, req)
}

// UpdateCompany calls salesorder.v1.CompanyService.UpdateCompany.
func (c *companyServiceClient) UpdateCompany(ctx context.Context, req *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error) {
	return c.updateCompany.CallUnary(ctx, req)
}

// DeleteCompany calls salesorder.v1.CompanyService.DeleteCompany.
func (c *companyServiceClient) DeleteCompany(ctx context.Context, req *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error) {
	return c.deleteCompany.CallUnary(ctx, req)
}

// CompanyServiceHandler is an implementation of the salesorder.v1.CompanyService service.
type CompanyServiceHandler interface {
	// ListCompanies:分頁列出公司,可依 status / keyword(name、identifier 模糊)篩選。
	ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error)
	// GetCompany:取得單一公司。
	GetCompany(context.Context, *connect.Request[v1.GetCompanyRequest]) (*connect.Response[v1.GetCompanyResponse], error)
	// CreateCompany:建立公司。
	CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error)
	// UpdateCompany:更新公司(name、tax_id、status;identifier 建立後不可修改)。
	UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error)
	// DeleteCompany:刪除公司。
	DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error)
}

// NewCompanyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCompanyServiceHandler(svc CompanyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	companyServiceMethods := v1.File_salesorder_v1_company_proto.Services().ByName("CompanyService").Methods()
	companyServiceListCompaniesHandler := connect.NewUnaryHandler(
		CompanyServiceListCompaniesProcedure,
		svc.ListCompanies,
		connect.WithSchema(companyServiceMethods.ByName("ListCompanies")),
		connect.WithHandlerOptions(opts...),
	)
	companyServiceGetCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceGetCompanyProcedure,
		svc.GetCompany,
		connect.WithSchema(companyServiceMethods.ByName("GetCompany")),
		connect.WithHandlerOptions(opts...),
	)
	companyServiceCreateCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceCreateCompanyProcedure,
		svc.CreateCompany,
		connect.WithSchema(companyServiceMethods.ByName("CreateCompany")),
		connect.WithHandlerOptions(opts...),
	)
	companyServiceUpdateCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceUpdateCompanyProcedure,
		svc.UpdateCompany,
		connect.WithSchema(companyServiceMethods.ByName("UpdateCompany")),
		connect.WithHandlerOptions(opts...),
	)
	companyServiceDeleteCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceDeleteCompanyProcedure,
		svc.DeleteCompany,
		connect.WithSchema(companyServiceMethods.ByName("DeleteCompany")),
		connect.WithHandlerOptions(opts...),
	)
	return "/salesorder.v1.CompanyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CompanyServiceListCompaniesProcedure:
			companyServiceListCompaniesHandler.ServeHTTP(w, r)
		case CompanyServiceGetCompanyProcedure:
			companyServiceGetCompanyHandler.ServeHTTP(w, r)
		case CompanyServiceCreateCompanyProcedure:
			companyServiceCreateCompanyHandler.ServeHTTP(w, r)
		case CompanyServiceUpdateCompanyProcedure:
			companyServiceUpdateCompanyHandler.ServeHTTP(w, r)
		case CompanyServiceDeleteCompanyProcedure:
			companyServiceDeleteCompanyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCompanyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCompanyServiceHandler struct{}

func (UnimplementedCompanyServiceHandler) ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.CompanyService.ListCompanies is not implemented"))
}

func (UnimplementedCompanyServiceHandler) GetCompany(context.Context, *connect.Request[v1.GetCompanyRequest]) (*connect.Response[v1.GetCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.CompanyService.GetCompany is not implemented"))
}

func (UnimplementedCompanyServiceHandler) CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.CompanyService.CreateCompany is not implemented"))
}

func (UnimplementedCompanyServiceHandler) UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.CompanyService.UpdateCompany is not implemented"))
}

func (UnimplementedCompanyServiceHandler) DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.CompanyService.DeleteCompany is not implemented"))
}

// DepartmentServiceClient is a client for the salesorder.v1.DepartmentService service.
type DepartmentServiceClient interface {
	// ListDepartments:分頁列出部門,可依 company_id 篩選。
	ListDepartments(context.Context, *connect.Request[v1.ListDepartmentsRequest]) (*connect.Response[v1.ListDepartmentsResponse], error)
	// GetDepartment:取得單一部門。
	GetDepartment(context.Context, *connect.Request[v1.GetDepartmentRequest]) (*connect.Response[v1.GetDepartmentResponse], error)
	// CreateDepartment:建立部門(需指定所屬公司)。
	CreateDepartment(context.Context, *connect.Request[v1.CreateDepartmentRequest]) (*connect.Response[v1.CreateDepartmentResponse], error)
	// UpdateDepartment:更新部門名稱。
	UpdateDepartment(context.Context, *connect.Request[v1.UpdateDepartmentRequest]) (*connect.Response[v1.UpdateDepartmentResponse], error)
	// DeleteDepartment:刪除部門。
	DeleteDepartment(context.Context, *connect.Request[v1.DeleteDepartmentRequest]) (*connect.Response[v1.DeleteDepartmentResponse], error)
}

// NewDepartmentServiceClient constructs a client for the salesorder.v1.DepartmentService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDepartmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DepartmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	departmentServiceMethods := v1.File_salesorder_v1_company_proto.Services().ByName("DepartmentService").Methods()
	return &departmentServiceClient{
		listDepartments: connect.NewClient[v1.ListDepartmentsRequest, v1.ListDepartmentsResponse](
			httpClient,
			baseURL+DepartmentServiceListDepartmentsProcedure,
			connect.WithSchema(departmentServiceMethods.ByName("ListDepartments")),
			connect.WithClientOptions(opts...),
		),
		getDepartment: connect.NewClient[v1.GetDepartmentRequest, v1.GetDepartmentResponse](
			httpClient,
			baseURL+DepartmentServiceGetDepartmentProcedure,
			connect.WithSchema(departmentServiceMethods.ByName("GetDepartment")),
			connect.WithClientOptions(opts...),
		),
		createDepartment: connect.NewClient[v1.CreateDepartmentRequest, v1.CreateDepartmentResponse](
			httpClient,
			baseURL+DepartmentServiceCreateDepartmentProcedure,
			connect.WithSchema(departmentServiceMethods.ByName("CreateDepartment")),
			connect.WithClientOptions(opts...),
		),
		updateDepartment: connect.NewClient[v1.UpdateDepartmentRequest, v1.UpdateDepartmentResponse](
			httpClient,
			baseURL+DepartmentServiceUpdateDepartmentProcedure,
			connect.WithSchema(departmentServiceMethods.ByName("UpdateDepartment")),
			connect.WithClientOptions(opts...),
		),
		deleteDepartment: connect.NewClient[v1.DeleteDepartmentRequest, v1.DeleteDepartmentResponse](
			httpClient,
			baseURL+DepartmentServiceDeleteDepartmentProcedure,
			connect.WithSchema(departmentServiceMethods.ByName("DeleteDepartment")),
			connect.WithClientOptions(opts...),
		),
	}
}

// departmentServiceClient implements DepartmentServiceClient.
type departmentServiceClient struct {
	listDepartments  *connect.Client[v1.ListDepartmentsRequest, v1.ListDepartmentsResponse]
	getDepartment    *connect.Client[v1.GetDepartmentRequest, v1.GetDepartmentResponse]
	createDepartment *connect.Client[v1.CreateDepartmentRequest, v1.CreateDepartmentResponse]
	updateDepartment *connect.Client[v1.UpdateDepartmentRequest, v1.UpdateDepartmentResponse]
	deleteDepartment *connect.Client[v1.DeleteDepartmentRequest, v1.DeleteDepartmentResponse]
}

// ListDepartments calls salesorder.v1.DepartmentService.ListDepartments.
func (c *departmentServiceClient) ListDepartments(ctx context.Context, req *connect.Request[v1.ListDepartmentsRequest]) (*connect.Response[v1.ListDepartmentsResponse], error) {
	return c.listDepartments.CallUnary(ctx, req)
}

// GetDepartment calls salesorder.v1.DepartmentService.GetDepartment.
func (c *departmentServiceClient) GetDepartment(ctx context.Context, req *connect.Request[v1.GetDepartmentRequest]) (*connect.Response[v1.GetDepartmentResponse], error) {
	return c.getDepartment.CallUnary(ctx, req)
}

// CreateDepartment calls salesorder.v1.DepartmentService.CreateDepartment.
func (c *departmentServiceClient) CreateDepartment(ctx context.Context, req *connect.Request[v1.CreateDepartmentRequest]) (*connect.Response[v1.CreateDepartmentResponse], error) {
	return c.createDepartment.CallUnary(ctx, req)
}

// UpdateDepartment calls salesorder.v1.DepartmentService.UpdateDepartment.
func (c *departmentServiceClient) UpdateDepartment(ctx context.Context, req *connect.Request[v1.UpdateDepartmentRequest]) (*connect.Response[v1.UpdateDepartmentResponse], error) {
	return c.updateDepartment.CallUnary(ctx, req)
}

// DeleteDepartment calls salesorder.v1.DepartmentService.DeleteDepartment.
func (c *departmentServiceClient) DeleteDepartment(ctx context.Context, req *connect.Request[v1.DeleteDepartmentRequest]) (*connect.Response[v1.DeleteDepartmentResponse], error) {
	return c.deleteDepartment.CallUnary(ctx, req)
}

// DepartmentServiceHandler is an implementation of the salesorder.v1.DepartmentService service.
type DepartmentServiceHandler interface {
	// ListDepartments:分頁列出部門,可依 company_id 篩選。
	ListDepartments(context.Context, *connect.Request[v1.ListDepartmentsRequest]) (*connect.Response[v1.ListDepartmentsResponse], error)
	// GetDepartment:取得單一部門。
	GetDepartment(context.Context, *connect.Request[v1.GetDepartmentRequest]) (*connect.Response[v1.GetDepartmentResponse], error)
	// CreateDepartment:建立部門(需指定所屬公司)。
	CreateDepartment(context.Context, *connect.Request[v1.CreateDepartmentRequest]) (*connect.Response[v1.CreateDepartmentResponse], error)
	// UpdateDepartment:更新部門名稱。
	UpdateDepartment(context.Context, *connect.Request[v1.UpdateDepartmentRequest]) (*connect.Response[v1.UpdateDepartmentResponse], error)
	// DeleteDepartment:刪除部門。
	DeleteDepartment(context.Context, *connect.Request[v1.DeleteDepartmentRequest]) (*connect.Response[v1.DeleteDepartmentResponse], error)
}

// NewDepartmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDepartmentServiceHandler(svc DepartmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	departmentServiceMethods := v1.File_salesorder_v1_company_proto.Services().ByName("DepartmentService").Methods()
	departmentServiceListDepartmentsHandler := connect.NewUnaryHandler(
		DepartmentServiceListDepartmentsProcedure,
		svc.ListDepartments,
		connect.WithSchema(departmentServiceMethods.ByName("ListDepartments")),
		connect.WithHandlerOptions(opts...),
	)
	departmentServiceGetDepartmentHandler := connect.NewUnaryHandler(
		DepartmentServiceGetDepartmentProcedure,
		svc.GetDepartment,
		connect.WithSchema(departmentServiceMethods.ByName("GetDepartment")),
		connect.WithHandlerOptions(opts...),
	)
	departmentServiceCreateDepartmentHandler := connect.NewUnaryHandler(
		DepartmentServiceCreateDepartmentProcedure,
		svc.CreateDepartment,
		connect.WithSchema(departmentServiceMethods.ByName("CreateDepartment")),
		connect.WithHandlerOptions(opts...),
	)
	departmentServiceUpdateDepartmentHandler := connect.NewUnaryHandler(
		DepartmentServiceUpdateDepartmentProcedure,
		svc.UpdateDepartment,
		connect.WithSchema(departmentServiceMethods.ByName("UpdateDepartment")),
		connect.WithHandlerOptions(opts...),
	)
	departmentServiceDeleteDepartmentHandler := connect.NewUnaryHandler(
		DepartmentServiceDeleteDepartmentProcedure,
		svc.DeleteDepartment,
		connect.WithSchema(departmentServiceMethods.ByName("DeleteDepartment")),
		connect.WithHandlerOptions(opts...),
	)
	return "/salesorder.v1.DepartmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DepartmentServiceListDepartmentsProcedure:
			departmentServiceListDepartmentsHandler.ServeHTTP(w, r)
		case DepartmentServiceGetDepartmentProcedure:
			departmentServiceGetDepartmentHandler.ServeHTTP(w, r)
		case DepartmentServiceCreateDepartmentProcedure:
			departmentServiceCreateDepartmentHandler.ServeHTTP(w, r)
		case DepartmentServiceUpdateDepartmentProcedure:
			departmentServiceUpdateDepartmentHandler.ServeHTTP(w, r)
		case DepartmentServiceDeleteDepartmentProcedure:
			departmentServiceDeleteDepartmentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDepartmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDepartmentServiceHandler struct{}

func (UnimplementedDepartmentServiceHandler) ListDepartments(context.Context, *connect.Request[v1.ListDepartmentsRequest]) (*connect.Response[v1.ListDepartmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.DepartmentService.ListDepartments is not implemented"))
}

func (UnimplementedDepartmentServiceHandler) GetDepartment(context.Context, *connect.Request[v1.GetDepartmentRequest]) (*connect.Response[v1.GetDepartmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.DepartmentService.GetDepartment is not implemented"))
}

func (UnimplementedDepartmentServiceHandler) CreateDepartment(context.Context, *connect.Request[v1.CreateDepartmentRequest]) (*connect.Response[v1.CreateDepartmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.DepartmentService.CreateDepartment is not implemented"))
}

func (UnimplementedDepartmentServiceHandler) UpdateDepartment(context.Context, *connect.Request[v1.UpdateDepartmentRequest]) (*connect.Response[v1.UpdateDepartmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.DepartmentService.UpdateDepartment is not implemented"))
}

func (UnimplementedDepartmentServiceHandler) DeleteDepartment(context.Context, *connect.Request[v1.DeleteDepartmentRequest]) (*connect.Response[v1.DeleteDepartmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("salesorder.v1.DepartmentService.DeleteDepartment is not implemented"))
}
