// Code generated by ent, DO NOT EDIT.

package customercounter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldCompanyID, v))
}

// NextSeq applies equality check predicate on the "next_seq" field. It's identical to NextSeqEQ.
func NextSeq(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldNextSeq, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldVersion, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLTE(FieldCompanyID, v))
}

// NextSeqEQ applies the EQ predicate on the "next_seq" field.
func NextSeqEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldNextSeq, v))
}

// NextSeqNEQ applies the NEQ predicate on the "next_seq" field.
func NextSeqNEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNEQ(FieldNextSeq, v))
}

// NextSeqIn applies the In predicate on the "next_seq" field.
func NextSeqIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldIn(FieldNextSeq, vs...))
}

// NextSeqNotIn applies the NotIn predicate on the "next_seq" field.
func NextSeqNotIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNotIn(FieldNextSeq, vs...))
}

// NextSeqGT applies the GT predicate on the "next_seq" field.
func NextSeqGT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGT(FieldNextSeq, v))
}

// NextSeqGTE applies the GTE predicate on the "next_seq" field.
func NextSeqGTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGTE(FieldNextSeq, v))
}

// NextSeqLT applies the LT predicate on the "next_seq" field.
func NextSeqLT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLT(FieldNextSeq, v))
}

// NextSeqLTE applies the LTE predicate on the "next_seq" field.
func NextSeqLTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLTE(FieldNextSeq, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLTE(FieldVersion, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerCounter) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerCounter) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerCounter) predicate.CustomerCounter {
	return predicate.CustomerCounter(sql.NotPredicates(p))
}
