// Code generated by ent, DO NOT EDIT.

package fleetdriver

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/salesorder/sales-order-1.0/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCompanyID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldDepartmentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldPhone, v))
}

// CurrentStatus applies equality check predicate on the "current_status" field. It's identical to CurrentStatusEQ.
func CurrentStatus(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCurrentStatus, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldCompanyID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotNull(FieldDepartmentID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContainsFold(FieldName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContainsFold(FieldPhone, v))
}

// CurrentStatusEQ applies the EQ predicate on the "current_status" field.
func CurrentStatusEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCurrentStatus, v))
}

// CurrentStatusNEQ applies the NEQ predicate on the "current_status" field.
func CurrentStatusNEQ(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldCurrentStatus, v))
}

// CurrentStatusIn applies the In predicate on the "current_status" field.
func CurrentStatusIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldCurrentStatus, vs...))
}

// CurrentStatusNotIn applies the NotIn predicate on the "current_status" field.
func CurrentStatusNotIn(vs ...string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldCurrentStatus, vs...))
}

// CurrentStatusGT applies the GT predicate on the "current_status" field.
func CurrentStatusGT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldCurrentStatus, v))
}

// CurrentStatusGTE applies the GTE predicate on the "current_status" field.
func CurrentStatusGTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldCurrentStatus, v))
}

// CurrentStatusLT applies the LT predicate on the "current_status" field.
func CurrentStatusLT(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldCurrentStatus, v))
}

// CurrentStatusLTE applies the LTE predicate on the "current_status" field.
func CurrentStatusLTE(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldCurrentStatus, v))
}

// CurrentStatusContains applies the Contains predicate on the "current_status" field.
func CurrentStatusContains(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContains(FieldCurrentStatus, v))
}

// CurrentStatusHasPrefix applies the HasPrefix predicate on the "current_status" field.
func CurrentStatusHasPrefix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasPrefix(FieldCurrentStatus, v))
}

// CurrentStatusHasSuffix applies the HasSuffix predicate on the "current_status" field.
func CurrentStatusHasSuffix(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldHasSuffix(FieldCurrentStatus, v))
}

// CurrentStatusEqualFold applies the EqualFold predicate on the "current_status" field.
func CurrentStatusEqualFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEqualFold(FieldCurrentStatus, v))
}

// CurrentStatusContainsFold applies the ContainsFold predicate on the "current_status" field.
func CurrentStatusContainsFold(v string) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldContainsFold(FieldCurrentStatus, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FleetDriver {
	return predicate.FleetDriver(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FleetDriver) predicate.FleetDriver {
	return predicate.FleetDriver(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FleetDriver) predicate.FleetDriver {
	return predicate.FleetDriver(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FleetDriver) predicate.FleetDriver {
	return predicate.FleetDriver(sql.NotPredicates(p))
}
